import type { CropContent } from '@/types/content';

export const guar: CropContent = {
  id: 'crop-guar',
  slug: 'guar',
  contentType: 'crop',
  title: 'Guar',
  scientificName: 'Cyamopsis tetragonoloba',
  alternativeNames: ['Cluster bean', 'Guwar'],
  category: 'Industrial crop',
  subcategory: 'Drought-tolerant annual legume',
  botanicalFamily: 'Fabaceae (legume family)',
  lifecycle: 'Annual',
  summary:
    'Guar is a drought-tolerant legume grown mainly on the rainfed margins of northwest India and Pakistan. Its seed endosperm yields a galactomannan gum used across food and industry, and the crop is unusual in that a subsistence-scale rainfed legume is priced by demand from oil and gas drilling.',
  introduction: [
    {
      type: 'paragraph',
      text: 'Guar is grown in country too dry and too unreliable for most crops, largely without irrigation, largely on smallholdings, and largely in one region: India accounts for the great majority of world production, concentrated in the semi-arid tracts of Rajasthan and neighbouring states.',
    },
    {
      type: 'paragraph',
      text: 'What makes it commercially unusual is where the value sits. The endosperm — roughly half the seed — is milled into guar gum, a galactomannan that thickens water at very low concentrations, and that property has made a rainfed legume into an industrial feedstock traded globally.',
    },
  ],
  keyFacts: [
    { label: 'Botanical family', value: 'Fabaceae (legume family)' },
    { label: 'Harvested part', value: 'Seed, for its endosperm' },
    {
      label: 'Endosperm fraction',
      value:
        'About half the seed; galactomannan is a large share of seed weight',
    },
    {
      label: 'Principal producing region',
      value: 'Semi-arid northwest India and adjoining Pakistan, mostly rainfed',
    },
    {
      label: 'Principal industrial outlet',
      value:
        'Guar gum for food, textiles, paper, water treatment and well stimulation',
    },
    {
      label: 'Nitrogen',
      value: 'Fixes atmospheric nitrogen; a rotation legume',
    },
  ],
  sections: [
    {
      id: 'why-grown',
      heading: 'A crop for land that will not carry others',
      body: [
        {
          type: 'paragraph',
          text: 'Guar tolerates heat and a short, erratic monsoon better than most pulses, and it produces something on land where a failed cereal would produce nothing. In the systems where it is grown it is part of the drought strategy rather than the main enterprise.',
        },
        {
          type: 'paragraph',
          text: 'It is also a legume in a rotation dominated by cereals and millets, so its nitrogen contribution and its break-crop effect matter locally regardless of what the gum market is doing.',
        },
      ],
    },
    {
      id: 'gum',
      heading: 'What guar gum is',
      body: [
        {
          type: 'paragraph',
          text: 'The seed splits into hull, germ and endosperm, and the endosperm is the fraction of value. It is milled into a powder whose galactomannan chains hydrate in cold water and raise viscosity at concentrations low enough to be an economic ingredient — which is the whole basis of the trade.',
        },
        {
          type: 'paragraph',
          text: 'The germ and hull are separated as by-products and used in animal feed. A guar processing plant is therefore a splitting and milling operation rather than a crushing one, and the crop has no oil fraction of significance.',
        },
      ],
    },
    {
      id: 'market',
      heading: 'Priced by an industry the growers are not in',
      body: [
        {
          type: 'paragraph',
          text: 'Guar gum is used to thicken and carry proppant in hydraulic fracturing fluid, and the expansion of shale drilling turned guar into one of India’s largest agricultural exports to the United States. Demand from that sector moves faster and further than food demand ever did.',
        },
        {
          type: 'paragraph',
          text: 'The consequence for growers is a price signal generated by drilling activity on another continent, arriving in a rainfed smallholder system with a fixed sowing window. Area planted responds to last season’s price, and the crop has a history of sharp boom and collapse for reasons entirely outside agriculture.',
        },
      ],
    },
    {
      id: 'agronomy',
      heading: 'Sowing and growth',
      body: [
        {
          type: 'paragraph',
          text: 'Guar is sown with the onset of the monsoon and matures on residual moisture. It is deep-rooting and recovers from mid-season dry spells that would end a shallower legume, but it is intolerant of waterlogging and does badly on heavy soils that hold water after intense rain.',
        },
        {
          type: 'paragraph',
          text: 'Determinate and indeterminate types are both grown. Determinate types concentrate pod set and suit mechanical harvest and a short season; indeterminate types keep flowering and hedge against an erratic monsoon at the cost of an uneven harvest.',
        },
      ],
    },
    {
      id: 'nutrition',
      heading: 'Nutrition and inoculation',
      body: [
        {
          type: 'paragraph',
          text: 'As a legume it fixes its own nitrogen where effective rhizobia are present, and in the traditional growing areas they generally are. Phosphorus is the nutrient most often limiting, and responses to it are more consistent than responses to nitrogen.',
        },
        {
          type: 'paragraph',
          text: 'Applying nitrogen to a nodulating stand suppresses fixation for no yield gain, which matters in a low-input system where any purchased input is a real cost against an uncertain crop.',
        },
      ],
    },
    {
      id: 'salinity',
      heading: 'Salinity and marginal land',
      body: [
        {
          type: 'paragraph',
          text: 'Guar carries useful tolerance of salinity and of alkaline soils, which is part of why it persists on land that has gone out of other production. Genotypes differ substantially in that tolerance, and it is an active breeding objective for the arid southwest of the United States as well as for South Asia.',
        },
        {
          type: 'paragraph',
          text: 'Tolerance is not immunity. Yields fall on saline ground, and the crop is chosen there because the alternative is a worse yield, not because salinity does not affect it.',
        },
      ],
    },
    {
      id: 'harvest',
      heading: 'Harvest and seed quality',
      body: [
        {
          type: 'paragraph',
          text: 'Pods are borne in clusters — the origin of the name cluster bean — and are cut or pulled when dry. Seed is threshed, cleaned and sold on splitting quality, because a processor is buying endosperm rather than seed weight.',
        },
        {
          type: 'paragraph',
          text: 'Immature, shrivelled or weathered seed splits poorly and yields less gum from the same tonnage, so drying and clean storage carry more value here than in a pulse sold for food.',
        },
      ],
    },
    {
      id: 'food-use',
      heading: 'The vegetable crop underneath',
      body: [
        {
          type: 'paragraph',
          text: 'Before it was an industrial feedstock guar was, and still is, a vegetable: young pods are eaten as a cooked green bean across northwest India, and the plant is also cut as fodder. Those uses do not enter international statistics and are invisible in gum-trade figures.',
        },
        {
          type: 'paragraph',
          text: 'A crop with a household food use, a fodder use and a globally traded industrial use is priced by only one of them, which is worth stating plainly when reading any production figure for it.',
        },
      ],
    },
  ],
  commonDiseases: [
    { type: 'plant-disease', slug: 'bacterial-leaf-spot' },
    { type: 'plant-disease', slug: 'anthracnose' },
    { type: 'plant-disease', slug: 'root-rot' },
  ],
  commonPests: [
    { type: 'pest', slug: 'aphids' },
    { type: 'pest', slug: 'whiteflies' },
    { type: 'pest', slug: 'pod-borer' },
    { type: 'pest', slug: 'leafhoppers' },
  ],
  suitableSoils: [
    { type: 'soil', slug: 'sandy-soil' },
    { type: 'soil', slug: 'loam-soil' },
    { type: 'soil', slug: 'saline-soil' },
  ],
  connections: [
    { type: 'nutrient', slug: 'nitrogen' },
    { type: 'nutrient', slug: 'phosphorus' },
    { type: 'climate', slug: 'monsoon' },
    { type: 'climate', slug: 'drought' },
    { type: 'climate', slug: 'heat-stress' },
    { type: 'farming-system', slug: 'dryland-farming' },
    { type: 'farming-system', slug: 'intercropping' },
    { type: 'post-harvest', slug: 'threshing-and-shelling' },
  ],
  relatedTopics: [
    { type: 'crop', slug: 'cowpea' },
    { type: 'crop', slug: 'millet' },
  ],
  glossaryTerms: ['crop-rotation'],
  geographicScope:
    'Chiefly northwest India and adjoining Pakistan, with smaller production in the arid southwestern United States and parts of Africa.',
  climateContext:
    'Semi-arid monsoon; deep-rooted and heat-tolerant, intolerant of waterlogging, with useful salinity tolerance.',
  limitations: [
    'The endosperm and galactomannan fractions vary widely with genotype and season; the ranges here describe the crop, not any consignment.',
    'Production is concentrated in one region and much of the vegetable and fodder use never enters statistics, so reported figures describe the gum trade more than the crop.',
    'Salinity tolerance differs substantially between genotypes and no general threshold applies.',
    'Prices are driven by industrial demand outside agriculture and are not predictable from agronomic conditions.',
  ],
  sourceReferences: [
    {
      sourceId: 'fao',
      citedFor: 'Guar production and arid-zone legume context',
    },
    { sourceId: 'icar', citedFor: 'Indian guar agronomy and varieties' },
    {
      sourceId: 'usda-ars',
      citedFor: 'Guar salinity tolerance and genotype research',
    },
    { sourceId: 'cabi', citedFor: 'Cyamopsis tetragonoloba compendium data' },
    { sourceId: 'usda-plants', citedFor: 'Classification and nomenclature' },
  ],
  reviewedAt: '2026-09-02',
  updatedAt: '2026-09-02',
  editorialStatus: 'published',
  seo: {
    title: 'Guar',
    description:
      'Cyamopsis tetragonoloba as a crop: rainfed arid-zone legume, the galactomannan endosperm, guar gum, and a price set by drilling demand.',
    keywords: [
      'guar',
      'Cyamopsis tetragonoloba',
      'cluster bean',
      'guar gum',
      'galactomannan',
    ],
  },
  structuredData: { article: true },
};
