/**
 * Phase 4B — comparison intelligence.
 *
 * Curated, evidence-based comparisons of compatible entities. Comparison FIELDS
 * are resolved from the source entities (or dataset snapshots), never duplicated
 * by hand. Comparisons are hand-selected for value — NOT generated by Cartesian
 * product of every possible pair.
 */

export type ComparisonEntityType =
  'crop' | 'cultivar' | 'breed' | 'fertilizer' | 'soil' | 'country';

export interface Comparison {
  comparisonId: string;
  slug: string;
  entityType: ComparisonEntityType;
  title: string;
  /** Source-entity slugs (or ISO3 codes for country comparisons). ≥ 2. */
  comparedEntityIds: string[];
  purpose: string;
  /** Dimension keys to render (resolved from the source entities). */
  dimensions: string[];
  /** For country comparisons: the indicator ids compared. */
  indicators?: string[];
  /** Reference year for volatile country data (a common year is enforced). */
  referenceYear?: number;
  methodology: string;
  limitations: string[];
  sourceReferences: { sourceId: string; citedFor?: string }[];
  reviewedAt: string;
  updatedAt: string;
  editorialStatus: 'draft' | 'in-review' | 'published';
  seo: { title: string; description: string };
}

/**
 * Compact authored form. The registry fills comparisonId, dates, editorial
 * status, and derives unique SEO — keeping curated entries small while
 * guaranteeing metadata uniqueness.
 */
export interface ComparisonSeed {
  slug: string;
  entityType: ComparisonEntityType;
  title: string;
  comparedEntityIds: string[];
  purpose: string;
  dimensions?: string[];
  indicators?: string[];
  referenceYear?: number;
  methodology: string;
  limitations: string[];
  sourceReferences: { sourceId: string; citedFor?: string }[];
}

/** A resolved comparison ready for rendering. */
export interface ResolvedComparison {
  comparison: Comparison;
  columns: { id: string; title: string; route: string }[];
  rows: {
    key: string;
    label: string;
    unit?: string;
    cells: (string | null)[];
    /** For country rows: the reference year the cells were taken from. */
    year?: number;
    note?: string;
  }[];
  /** Source/version provenance line for country comparisons. */
  provenance?: {
    sourceDataset: string;
    sourceVersion: string;
    retrievedAt: string;
  };
}
