import type { PestContent } from '@/types/content';

export const granaryWeevil: PestContent = {
  id: 'pest-granary-weevil',
  slug: 'granary-weevil',
  contentType: 'pest',
  title: 'Granary Weevil',
  scientificName: 'Sitophilus granarius (Coleoptera: Curculionidae)',
  alternativeNames: ['Sitophilus granarius', 'Grain weevil', 'Wheat weevil'],
  category: 'Insect pest',
  subcategory: 'Internal-feeding stored-grain weevil',
  pestGroup: 'Insect — Coleoptera (Curculionidae)',
  summary:
    'The granary weevil is a flightless primary pest of stored cereals in temperate regions. Its larvae develop hidden inside whole kernels, and because it cannot fly it spreads almost entirely through the movement of infested grain.',
  introduction: [
    {
      type: 'paragraph',
      text: 'The granary weevil is a primary, internal feeder of stored cereals and the weevil most associated with temperate grain stores. As with its relatives, the female chews a cavity into a sound, whole kernel, deposits an egg, and seals it; the larva develops entirely inside that kernel and the adult chews an exit hole to emerge. It therefore attacks clean, undamaged grain rather than waiting for grain to be broken.',
    },
    {
      type: 'paragraph',
      text: 'Its defining characteristic is that it cannot fly. The wing covers are fused and there are no functional flight wings, so this species does not colonise stores from the air and does not infest crops in the field. It spreads through the movement of infested grain, through contaminated equipment, sacks, and vehicles, and from residues left in the fabric of the store itself. That makes it, unusually among storage pests, a problem largely propagated by human handling — which is also what makes store sanitation so effective against it.',
    },
  ],
  keyFacts: [
    {
      label: 'Group',
      value: 'Insects, order Coleoptera, family Curculionidae',
    },
    {
      label: 'Feeding type',
      value: 'Primary (internal) feeder — attacks sound, whole kernels',
    },
    {
      label: 'Damaging stage',
      value: 'Larva, developing concealed inside an individual kernel',
    },
    {
      label: 'Distinguishing feature',
      value:
        'Uniformly dark reddish-brown to black, without the paler wing-cover spots of its relatives',
    },
    {
      label: 'Dispersal',
      value:
        'Flightless — spreads via infested grain, equipment, sacks, and store residues',
    },
    {
      label: 'Distribution',
      value:
        'Principally temperate grain stores; does not infest crops in the field',
    },
    {
      label: 'Sign',
      value: 'Exit holes, hollow kernels, adults in sieved samples',
    },
  ],
  sections: [
    {
      id: 'identification-and-biology',
      heading: 'Identification and biology',
      body: [
        {
          type: 'paragraph',
          text: 'Adults are snouted weevils, uniformly dark reddish-brown to black and, importantly, without the paler reddish or orange wing-cover spots seen on the rice and maize weevils. The thorax bears elongated or oval punctures rather than the rounded pitting of those species. The wing covers are fused: the granary weevil cannot fly, and this is the most practically useful distinction from its close relatives. Larvae are legless white grubs that develop out of sight inside kernels.',
        },
        {
          type: 'paragraph',
          text: 'Egg laying, larval feeding, and pupation all occur within a single kernel, and the adult cuts its way out. Development proceeds faster in warm, moist grain and slower in cool, dry grain; this species is nonetheless better adapted to cooler conditions than the rice and maize weevils, which is why it predominates in temperate stores. The governing conditions and durations are commodity- and setting-specific and are not given here.',
        },
      ],
    },
    {
      id: 'damage-to-stored-commodities',
      heading: 'How it damages stored commodities',
      body: [
        {
          type: 'paragraph',
          text: 'Larvae eat out the interior of kernels, so infested grain loses weight and nutritional value, and grain held for seed can lose germination where the germ is consumed. Adults feed on grain as well. Damaged kernels may remain outwardly whole while being substantially hollow.',
        },
        {
          type: 'paragraph',
          text: 'Insect activity within a bulk releases heat and moisture. That moisture moves through the grain and collects, producing hot spots that are then hospitable to storage moulds, so an insect infestation regularly becomes a mould and quality problem in turn. The broken grain, flour, and dust generated by weevil feeding also supply the fines on which secondary feeders — flour beetles, sawtoothed grain beetles — depend, so the primary infestation opens the door to others.',
        },
        {
          type: 'paragraph',
          text: 'Stored wheat, barley, oats, rye, and maize are the commodities most commonly affected, consistent with the species being centred on temperate cereal stores.',
        },
      ],
    },
    {
      id: 'detection-and-monitoring',
      heading: 'Detection and monitoring',
      body: [
        {
          type: 'paragraph',
          text: 'The hidden-infestation problem applies here in full: eggs, larvae, and pupae are sealed inside intact kernels, so a sample can appear entirely clean while the lot is infested. Visual inspection picks up adults after they emerge, which is late. A clean-looking sample is not evidence of a clean lot.',
        },
        {
          type: 'paragraph',
          text: 'Monitoring accordingly relies on sieving samples for adults and fines, examining kernels for exit holes and hollowness, monitoring bulk temperature for developing hot spots, and trapping in the store. Because this species does not fly, trap catches reflect walking insects and the layout of a store matters to what is caught. Laboratory methods that reveal insects inside intact kernels are used where hidden infestation must be established.',
        },
        {
          type: 'paragraph',
          text: 'Since the granary weevil arrives with grain or persists in store residues rather than flying in, intake inspection and attention to the store fabric are the highest-value monitoring points.',
        },
      ],
    },
    {
      id: 'management-principles',
      heading: 'Management principles',
      body: [
        {
          type: 'paragraph',
          text: 'A flightless pest that spreads through handling is, in principle, a pest that hygiene can control. Management follows integrated pest management and is overwhelmingly preventive.',
        },
        {
          type: 'list',
          items: [
            'Sanitation of empty stores before intake is especially effective here: remove residual grain, dust, and spillage from cracks, ledges, floors, augers, elevators, and vehicles, because carry-over residues are the principal reservoir',
            'Clean sacks, containers, and handling equipment, which are otherwise a route of spread for a pest that cannot fly',
            'Inspect incoming lots and reject or segregate infested consignments rather than mixing them into sound stock',
            'Dry to the level set by the applicable grade standard or national storage guidance for the commodity and storage duration, and keep the grain dry',
            'Cool the bulk and manage moisture migration',
            'Use sealed or hermetic storage where appropriate to restrict the atmosphere available to insects',
            'Clean grain to remove fines and broken kernels before storage',
            'Monitor temperature and sample regularly',
          ],
        },
        {
          type: 'callout',
          tone: 'important',
          title: 'Fumigation and insecticide use are regulated activities',
          text: 'Fumigants used against stored-grain insects are acutely hazardous and strictly regulated. Their use requires appropriately licensed or certified operators and must follow the product label and the applicable national regulation. AgricultureID does not provide fumigant or insecticide names, doses, rates, exposure times, or procedures.',
        },
      ],
    },
  ],
  hostCrops: [
    { type: 'crop', slug: 'wheat' },
    { type: 'crop', slug: 'barley' },
    { type: 'crop', slug: 'oats' },
    { type: 'crop', slug: 'rye' },
    { type: 'crop', slug: 'maize' },
  ],
  connections: [
    { type: 'post-harvest', slug: 'stored-grain-insects' },
    { type: 'post-harvest', slug: 'storage-moulds-and-mycotoxins' },
    { type: 'post-harvest', slug: 'grain-storage' },
    { type: 'post-harvest', slug: 'hermetic-storage' },
    { type: 'post-harvest', slug: 'grain-cleaning' },
    { type: 'post-harvest', slug: 'moisture-content-and-equilibrium' },
  ],
  relatedTopics: [
    { type: 'pest', slug: 'rice-weevil' },
    { type: 'pest', slug: 'maize-weevil' },
    { type: 'pest', slug: 'lesser-grain-borer' },
    { type: 'pest', slug: 'weevils' },
  ],
  glossaryTerms: ['integrated-pest-management'],
  geographicScope:
    'Principally temperate grain-storing regions worldwide; less important in hot climates, where the rice and maize weevils tend to predominate. Local status varies by country.',
  climateContext:
    'Better adapted to cooler storage conditions than its close relatives, which is why it dominates temperate stores; warm, moist grain still accelerates population growth.',
  limitations: [
    'This is a general reference overview of the species, not storage guidance for a specific commodity, store type, climate, or jurisdiction.',
    'No development times, temperature or moisture thresholds, or population figures are given here, because meaningful values depend on the commodity, climate, storage duration, and applicable standard.',
    'The absence of wing-cover spots and inability to fly are useful pointers, but confident species identification of Sitophilus weevils requires specialist examination.',
    'Treatment decisions, thresholds, and any fumigant or insecticide use are jurisdiction-specific, require licensed operators where applicable, and are not provided here.',
  ],
  sourceReferences: [
    { sourceId: 'cabi', citedFor: 'Biology, hosts, damage, and distribution' },
    { sourceId: 'eppo-gd', citedFor: 'Nomenclature and distribution' },
    {
      sourceId: 'ahdb',
      citedFor: 'Temperate grain storage and store hygiene context',
    },
    {
      sourceId: 'umn-extension',
      citedFor: 'Stored-grain insect monitoring and management context',
    },
    {
      sourceId: 'fao',
      citedFor: 'Post-harvest loss and grain storage context',
    },
  ],
  reviewedAt: '2026-07-13',
  updatedAt: '2026-07-13',
  editorialStatus: 'published',
  seo: {
    title: 'Granary Weevil (Sitophilus granarius)',
    description:
      'Granary weevil explained: a flightless primary pest of temperate grain stores that develops inside kernels and spreads through infested grain and residues.',
    keywords: [
      'granary weevil',
      'Sitophilus granarius',
      'grain weevil',
      'stored grain pest',
      'flightless',
    ],
  },
  structuredData: { article: true },
};
