import type { PestContent } from '@/types/content';

export const sawtoothedGrainBeetle: PestContent = {
  id: 'pest-sawtoothed-grain-beetle',
  slug: 'sawtoothed-grain-beetle',
  contentType: 'pest',
  title: 'Sawtoothed Grain Beetle',
  scientificName: 'Oryzaephilus surinamensis (Coleoptera: Silvanidae)',
  alternativeNames: ['Oryzaephilus surinamensis', 'Saw-toothed grain beetle'],
  category: 'Insect pest',
  subcategory: 'Secondary (external) stored-product beetle',
  pestGroup: 'Insect — Coleoptera (Silvanidae)',
  summary:
    'The sawtoothed grain beetle is a secondary stored-product pest that feeds on broken grain, fines, and processed foods rather than sound whole kernels. Its flat body lets it penetrate packaging and reach residues in crevices.',
  introduction: [
    {
      type: 'paragraph',
      text: 'The sawtoothed grain beetle is a common secondary — external — feeder in grain stores, warehouses, and food premises worldwide. Like the flour beetles, it is generally unable to attack sound, undamaged whole kernels. It depends instead on grain that has already been broken or damaged, on the fines and dust generated by handling, and on processed and milled foods. Its named feature, a row of saw-like tooth projections along each side of the thorax, is diagnostic under magnification.',
    },
    {
      type: 'paragraph',
      text: 'Two practical characteristics define the problems it causes. First, its dependence on damaged material means its appearance in whole grain usually points backwards to an earlier cause — a hidden primary infestation, or mechanical damage during handling and drying. Second, it is remarkably flat and small, which allows it to work into crevices, seams, and packaging that would exclude bulkier insects. It is a well-known invader of packaged food, entering through folds and seams rather than being present when the pack was filled.',
    },
  ],
  keyFacts: [
    {
      label: 'Group',
      value: 'Insects, order Coleoptera, family Silvanidae',
    },
    {
      label: 'Feeding type',
      value:
        'Secondary (external) feeder — generally cannot attack sound, undamaged whole kernels',
    },
    {
      label: 'What it exploits',
      value:
        'Broken and damaged grain, fines and dust, milled and processed foods, oilseeds and dried fruit',
    },
    {
      label: 'Diagnostic meaning',
      value:
        'Its presence in whole grain usually signals prior damage from a primary feeder or from handling',
    },
    {
      label: 'Distinguishing feature',
      value:
        'Slender, very flat brown beetle with saw-like teeth along each side of the thorax',
    },
    {
      label: 'Notable habit',
      value:
        'Flat body allows entry into packaging seams and deep into crevices and residues',
    },
    {
      label: 'Sign',
      value: 'Small active beetles in fines, residues, and packaged goods',
    },
  ],
  sections: [
    {
      id: 'identification-and-biology',
      heading: 'Identification and biology',
      body: [
        {
          type: 'paragraph',
          text: 'Adults are slender, strongly flattened, brown beetles. The characteristic feature is the thorax, which bears a row of saw-like tooth projections along each side; this is visible under magnification and gives the species its name. Larvae are small, slender, and pale with darker markings, and they move freely through the commodity rather than developing inside kernels.',
        },
        {
          type: 'paragraph',
          text: 'The species is closely similar to the merchant grain beetle, Oryzaephilus mercator, with which it commonly co-occurs and is easily confused. Separation depends on fine characters of the head behind the eyes and is a task for careful or specialist examination. The two differ somewhat in the commodities they favour — the merchant grain beetle is more associated with oilseeds, nuts, and processed products — but this tendency is not a reliable basis for identification.',
        },
        {
          type: 'paragraph',
          text: 'Eggs are laid loose in the commodity, in fines, or in crevices, and all stages live externally. Populations build fastest in warm conditions and where residues and fines accumulate. Adults are long-lived by the standards of storage insects, which contributes to persistence in premises. The governing conditions and durations are setting-specific and are not stated here.',
        },
      ],
    },
    {
      id: 'damage-to-stored-commodities',
      heading: 'How it damages stored commodities',
      body: [
        {
          type: 'paragraph',
          text: 'Because it works on already-damaged material, the direct weight loss attributable to this species in whole grain is usually modest compared with what primary feeders remove. Its significance lies more in contamination and in commercial acceptability: beetles, cast skins, and frass in grain, in milled products, and in retail packs cause rejection and complaints. In stored grain it concentrates where fines gather, and it feeds on the germ of broken kernels, so seed lots can lose viability.',
        },
        {
          type: 'paragraph',
          text: 'The indirect route matters here as with other stored-product insects. Insect activity in a bulk adds heat and moisture; that moisture migrates and forms hot spots; hot spots then favour storage moulds, so what began as an insect issue develops into a mould and quality issue. Infestations in whole grain should therefore prompt a search for the primary damage that made the grain hospitable in the first place, rather than being treated as the whole problem.',
        },
        {
          type: 'paragraph',
          text: 'Stored wheat, maize, rice, barley, and oats are commonly affected, along with groundnuts, oilseeds, dried fruit, and a wide range of processed cereal foods.',
        },
      ],
    },
    {
      id: 'detection-and-monitoring',
      heading: 'Detection and monitoring',
      body: [
        {
          type: 'paragraph',
          text: 'External-living species are comparatively straightforward to detect: adults are mobile and visible, and sieving samples, inspecting fines and residues, and trapping all find them. Pheromone and food-based lures are available for Oryzaephilus and are used in stores and food premises. The beetle is small and flat, however, so inspection must reach into crevices, seams, and the underside of equipment, where it and its residues persist.',
        },
        {
          type: 'paragraph',
          text: 'As with the flour beetles, the interpretation is the valuable part. Sawtoothed grain beetles in a bulk of whole grain warrant a search for hidden primary infestation — exit holes, hollow or light kernels, dust, warm patches — and for handling and drying practices that are cracking grain. And the standard caution applies to that search: a clean-looking sample of whole grain can still conceal a primary infestation developing inside the kernels.',
        },
      ],
    },
    {
      id: 'management-principles',
      heading: 'Management principles',
      body: [
        {
          type: 'paragraph',
          text: 'Management rests on removing the damaged material and residues the species needs, within the general integrated pest management approach for stores and food premises.',
        },
        {
          type: 'list',
          items: [
            'Sanitation is central: clear fines, dust, spilled grain, and food residues from cracks, seams, ledges, augers, elevators, and machinery, since these are the reservoirs that sustain populations',
            'Clean grain to remove fines and broken kernels before storage, and limit mechanical damage in handling and drying',
            'Address any underlying primary infestation, since this beetle is often a consequence of it',
            'Reject or segregate infested incoming lots rather than mixing them into sound stock',
            'Use sound, well-sealed packaging and rotate stock, given the ability of this species to enter packs through seams',
            'Dry to the level set by the applicable grade standard or national storage guidance for the commodity and storage duration, and cool the bulk',
            'Use sealed or hermetic storage where appropriate, and monitor with traps and regular sampling of fines and residues',
          ],
        },
        {
          type: 'callout',
          tone: 'important',
          title: 'Fumigation and insecticide use are regulated activities',
          text: 'Fumigants used against stored-product insects are acutely hazardous and strictly regulated. Their use requires appropriately licensed or certified operators and must follow the product label and the applicable national regulation. AgricultureID does not provide fumigant or insecticide names, doses, rates, exposure times, or procedures.',
        },
      ],
    },
  ],
  hostCrops: [
    { type: 'crop', slug: 'wheat' },
    { type: 'crop', slug: 'maize' },
    { type: 'crop', slug: 'rice' },
    { type: 'crop', slug: 'barley' },
    { type: 'crop', slug: 'oats' },
    { type: 'crop', slug: 'groundnut' },
  ],
  connections: [
    { type: 'post-harvest', slug: 'stored-grain-insects' },
    { type: 'post-harvest', slug: 'storage-moulds-and-mycotoxins' },
    { type: 'post-harvest', slug: 'grain-storage' },
    { type: 'post-harvest', slug: 'hermetic-storage' },
    { type: 'post-harvest', slug: 'grain-cleaning' },
    { type: 'post-harvest', slug: 'packing-and-packaging' },
  ],
  relatedTopics: [
    { type: 'pest', slug: 'red-flour-beetle' },
    { type: 'pest', slug: 'lesser-grain-borer' },
    { type: 'pest', slug: 'indianmeal-moth' },
    { type: 'pest', slug: 'granary-weevil' },
  ],
  glossaryTerms: ['integrated-pest-management'],
  geographicScope:
    'Cosmopolitan in grain stores, warehouses, and food premises; local status, commodity mix, and practice vary by country.',
  climateContext:
    'Favoured by warm conditions and by accumulated fines and residues; cool, clean, dry storage is markedly less hospitable.',
  limitations: [
    'This is a general reference overview of the species, not storage or food-premises guidance for a specific commodity, facility, or jurisdiction.',
    'No development times, temperature or moisture thresholds, or population figures are given here, because meaningful values depend on the commodity, climate, storage duration, and applicable standard.',
    'Sources differ on whether this species can damage the germ of otherwise sound kernels; it is treated here as a secondary feeder dependent on damaged grain and fines, which is the mainstream position, but the boundary is not absolute.',
    'The sawtoothed and merchant grain beetles are closely similar and frequently co-occur; reliable separation requires careful or specialist examination.',
  ],
  sourceReferences: [
    { sourceId: 'cabi', citedFor: 'Biology, hosts, damage, and distribution' },
    {
      sourceId: 'uc-ipm',
      citedFor: 'Stored-product beetle identification and IPM principles',
    },
    {
      sourceId: 'umn-extension',
      citedFor: 'Stored-product insect monitoring and sanitation context',
    },
    { sourceId: 'eppo-gd', citedFor: 'Nomenclature and distribution' },
    {
      sourceId: 'fao',
      citedFor: 'Post-harvest loss and grain storage context',
    },
  ],
  reviewedAt: '2026-07-13',
  updatedAt: '2026-07-13',
  editorialStatus: 'published',
  seo: {
    title: 'Sawtoothed Grain Beetle (O. surinamensis)',
    description:
      'Sawtoothed grain beetle explained: a secondary feeder on broken grain and fines, its packaging-invading habit, what its presence implies, and management.',
    keywords: [
      'sawtoothed grain beetle',
      'Oryzaephilus surinamensis',
      'secondary feeder',
      'stored product pest',
      'packaging pest',
    ],
  },
  structuredData: { article: true },
};
