/**
 * Genus to family, as the taxonomic authorities reported it.
 *
 * A pinned contract that fails closed. The crops validator checks every
 * identity's family against this map, and a genus with no pin is an error
 * rather than a pass — so a new crop cannot arrive with an unchecked family.
 *
 * The check exists because a wrong family is invisible without one. Changing a
 * cereal's family from Poaceae to Fabaceae leaves a record that is well-formed,
 * plausibly spelled and completely wrong, and every structural rule in the gate
 * passed it.
 *
 * Regenerated from the verification runs; each value is the family the
 * authority returned alongside the accepted name. `Triticosecale` is written
 * without its hybrid sign because the validator strips the sign before the
 * lookup: the sign says the genus is a cross, not which family it is in.
 */
export const GENUS_FAMILY: Record<string, string> = {
  Abelmoschus: 'Malvaceae',
  Actinidia: 'Actinidiaceae',
  Agave: 'Asparagaceae',
  Agropyron: 'Poaceae',
  Allium: 'Amaryllidaceae',
  Aloe: 'Asphodelaceae',
  Amaranthus: 'Amaranthaceae',
  Anacardium: 'Anacardiaceae',
  Ananas: 'Bromeliaceae',
  Anethum: 'Apiaceae',
  Annona: 'Annonaceae',
  Apium: 'Apiaceae',
  Arachis: 'Fabaceae',
  Armoracia: 'Brassicaceae',
  Aronia: 'Rosaceae',
  Artocarpus: 'Moraceae',
  Arundo: 'Poaceae',
  Asparagus: 'Asparagaceae',
  Avena: 'Poaceae',
  Averrhoa: 'Oxalidaceae',
  Basella: 'Basellaceae',
  Benincasa: 'Cucurbitaceae',
  Bertholletia: 'Lecythidaceae',
  Beta: 'Amaranthaceae',
  Boehmeria: 'Urticaceae',
  Brassica: 'Brassicaceae',
  Bromus: 'Poaceae',
  Cajanus: 'Fabaceae',
  Camelina: 'Brassicaceae',
  Camellia: 'Theaceae',
  Canavalia: 'Fabaceae',
  Canna: 'Cannaceae',
  Cannabis: 'Cannabaceae',
  Capparis: 'Capparaceae',
  Capsicum: 'Solanaceae',
  Carica: 'Caricaceae',
  Carthamus: 'Asteraceae',
  Carum: 'Apiaceae',
  Carya: 'Juglandaceae',
  Castanea: 'Fagaceae',
  Ceiba: 'Malvaceae',
  Cenchrus: 'Poaceae',
  Chenopodium: 'Amaranthaceae',
  Chloris: 'Poaceae',
  Cicer: 'Fabaceae',
  Cichorium: 'Asteraceae',
  Cinnamomum: 'Lauraceae',
  Citrullus: 'Cucurbitaceae',
  Citrus: 'Rutaceae',
  Cocos: 'Arecaceae',
  Coffea: 'Rubiaceae',
  Coix: 'Poaceae',
  Cola: 'Malvaceae',
  Coleus: 'Lamiaceae',
  Colocasia: 'Araceae',
  Corchorus: 'Malvaceae',
  Coriandrum: 'Apiaceae',
  Corylus: 'Betulaceae',
  Crataegus: 'Rosaceae',
  Crocus: 'Iridaceae',
  Cucumis: 'Cucurbitaceae',
  Cucurbita: 'Cucurbitaceae',
  Cuminum: 'Apiaceae',
  Curcuma: 'Zingiberaceae',
  Cyamopsis: 'Fabaceae',
  Cydonia: 'Rosaceae',
  Cynara: 'Asteraceae',
  Dactylis: 'Poaceae',
  Daucus: 'Apiaceae',
  Desmodium: 'Fabaceae',
  Digitaria: 'Poaceae',
  Dimocarpus: 'Sapindaceae',
  Dioscorea: 'Dioscoreaceae',
  Diospyros: 'Ebenaceae',
  Durio: 'Malvaceae',
  Echinochloa: 'Poaceae',
  Elaeis: 'Arecaceae',
  Elettaria: 'Zingiberaceae',
  Eleusine: 'Poaceae',
  Eragrostis: 'Poaceae',
  Eriobotrya: 'Rosaceae',
  Eruca: 'Brassicaceae',
  Eutrema: 'Brassicaceae',
  Fagopyrum: 'Polygonaceae',
  Ficus: 'Moraceae',
  Foeniculum: 'Apiaceae',
  Fragaria: 'Rosaceae',
  Garcinia: 'Clusiaceae',
  Glycine: 'Fabaceae',
  Gossypium: 'Malvaceae',
  Guizotia: 'Asteraceae',
  Helianthus: 'Asteraceae',
  Hevea: 'Euphorbiaceae',
  Hippophae: 'Elaeagnaceae',
  Hordeum: 'Poaceae',
  Humulus: 'Cannabaceae',
  Ilex: 'Aquifoliaceae',
  Illicium: 'Schisandraceae',
  Ipomoea: 'Convolvulaceae',
  Jatropha: 'Euphorbiaceae',
  Juglans: 'Juglandaceae',
  Lablab: 'Fabaceae',
  Lactuca: 'Asteraceae',
  Lagenaria: 'Cucurbitaceae',
  Lathyrus: 'Fabaceae',
  Laurus: 'Lauraceae',
  Lavandula: 'Lamiaceae',
  Lepidium: 'Brassicaceae',
  Linum: 'Linaceae',
  Litchi: 'Sapindaceae',
  Lolium: 'Poaceae',
  Lotus: 'Fabaceae',
  Luffa: 'Cucurbitaceae',
  Lupinus: 'Fabaceae',
  Macadamia: 'Proteaceae',
  Macrotyloma: 'Fabaceae',
  Malus: 'Rosaceae',
  Mangifera: 'Anacardiaceae',
  Manihot: 'Euphorbiaceae',
  Manilkara: 'Sapotaceae',
  Maranta: 'Marantaceae',
  Matricaria: 'Asteraceae',
  Medicago: 'Fabaceae',
  Megathyrsus: 'Poaceae',
  Melilotus: 'Fabaceae',
  Mentha: 'Lamiaceae',
  Miscanthus: 'Poaceae',
  Momordica: 'Cucurbitaceae',
  Morus: 'Moraceae',
  Mucuna: 'Fabaceae',
  Musa: 'Musaceae',
  Mutarda: 'Brassicaceae',
  Myristica: 'Myristicaceae',
  Nasturtium: 'Brassicaceae',
  Nephelium: 'Sapindaceae',
  Nicotiana: 'Solanaceae',
  Nigella: 'Ranunculaceae',
  Ocimum: 'Lamiaceae',
  Olea: 'Oleaceae',
  Onobrychis: 'Fabaceae',
  Origanum: 'Lamiaceae',
  Oryza: 'Poaceae',
  Oxalis: 'Oxalidaceae',
  Pachyrhizus: 'Fabaceae',
  Panicum: 'Poaceae',
  Paspalum: 'Poaceae',
  Passiflora: 'Passifloraceae',
  Pastinaca: 'Apiaceae',
  Perilla: 'Lamiaceae',
  Persea: 'Lauraceae',
  Petroselinum: 'Apiaceae',
  Phacelia: 'Boraginaceae',
  Phaseolus: 'Fabaceae',
  Phleum: 'Poaceae',
  Phoenix: 'Arecaceae',
  Physalis: 'Solanaceae',
  Pimpinella: 'Apiaceae',
  Pinus: 'Pinaceae',
  Piper: 'Piperaceae',
  Pistacia: 'Anacardiaceae',
  Poa: 'Poaceae',
  Portulaca: 'Portulacaceae',
  Pouteria: 'Sapotaceae',
  Prunus: 'Rosaceae',
  Psidium: 'Myrtaceae',
  Psophocarpus: 'Fabaceae',
  Punica: 'Lythraceae',
  Pyrus: 'Rosaceae',
  Raphanus: 'Brassicaceae',
  Rheum: 'Polygonaceae',
  Ribes: 'Grossulariaceae',
  Ricinus: 'Euphorbiaceae',
  Rubus: 'Rosaceae',
  Sabdariffa: 'Malvaceae',
  Saccharum: 'Poaceae',
  Salvia: 'Lamiaceae',
  Sambucus: 'Viburnaceae',
  Secale: 'Poaceae',
  Selenicereus: 'Cactaceae',
  Sesamum: 'Pedaliaceae',
  Setaria: 'Poaceae',
  Sicyos: 'Cucurbitaceae',
  Simmondsia: 'Simmondsiaceae',
  Sinapis: 'Brassicaceae',
  Solanum: 'Solanaceae',
  Sorghum: 'Poaceae',
  Spinacia: 'Amaranthaceae',
  Spondias: 'Anacardiaceae',
  Stevia: 'Asteraceae',
  Stylosanthes: 'Fabaceae',
  Syzygium: 'Myrtaceae',
  Talinum: 'Talinaceae',
  Tamarindus: 'Fabaceae',
  Theobroma: 'Malvaceae',
  Thymus: 'Lamiaceae',
  Trichosanthes: 'Cucurbitaceae',
  Trifolium: 'Fabaceae',
  Trigonella: 'Fabaceae',
  Triticosecale: 'Poaceae',
  Triticum: 'Poaceae',
  Tropaeolum: 'Tropaeolaceae',
  Ullucus: 'Basellaceae',
  Urochloa: 'Poaceae',
  Vaccinium: 'Ericaceae',
  Valeriana: 'Caprifoliaceae',
  Vanilla: 'Orchidaceae',
  Vicia: 'Fabaceae',
  Vigna: 'Fabaceae',
  Vitis: 'Vitaceae',
  Xanthosoma: 'Araceae',
  Zea: 'Poaceae',
  Zingiber: 'Zingiberaceae',
  Zizania: 'Poaceae',
  x: 'Brassicaceae',
};

/**
 * Grain and fibre market classes, which are not botanical taxa.
 *
 * A market class describes how a harvest is graded and traded — by hardness,
 * colour, sowing season, staple length. It is not a plant. "Hard Red Winter" is
 * a wheat class; every wheat in it is Triticum aestivum, and a crop record
 * carrying the class as a common name asserts that a grading category is a
 * species.
 *
 * The corpus does not publish these as entities, so there is nothing to check a
 * name against — which is why they are pinned here. The list is not exhaustive
 * and does not need to be: it closes the named cases, and the duplicate-taxon
 * rule closes the rest, because a market class has no botanical name of its own
 * and can only enter by borrowing one another identity already holds.
 */
export const MARKET_CLASS_NAMES: readonly string[] = [
  'hard red winter',
  'hard red spring',
  'soft red winter',
  'soft white',
  'hard white',
  'durum semolina',
  'no. 2 yellow',
  'yellow dent',
  'white dent',
  'flint corn',
  'upland cotton class',
  'pima class',
  'extra long staple',
  'long grain',
  'medium grain',
  'short grain',
  'malting barley',
  'feed barley',
  'food grade',
];
