/**
 * Genus to family, as the taxonomic authorities reported it.
 *
 * A pinned contract that fails closed. The crops validator checks every
 * identity's family against this map, and a genus with no pin is an error
 * rather than a pass — so a new crop cannot arrive with an unchecked family.
 *
 * The check exists because a wrong family is invisible without one. Changing a
 * cereal's family from Poaceae to Fabaceae leaves a record that is
 * well-formed, plausibly spelled and completely wrong, and every structural
 * rule in the gate passed it.
 *
 * Regenerated from the verification runs; each value is the family the
 * authority returned alongside the accepted name.
 */
export const GENUS_FAMILY: Record<string, string> = {
  // A nothogenus. Written without the hybrid sign because the validator strips
  // it before the lookup: the sign says the genus is a cross, not which family
  // it belongs to.
  Triticosecale: 'Poaceae',
  Abelmoschus: 'Malvaceae',
  Actinidia: 'Actinidiaceae',
  Allium: 'Amaryllidaceae',
  Aloe: 'Asphodelaceae',
  Amaranthus: 'Amaranthaceae',
  Anacardium: 'Anacardiaceae',
  Ananas: 'Bromeliaceae',
  Anethum: 'Apiaceae',
  Apium: 'Apiaceae',
  Arachis: 'Fabaceae',
  Artocarpus: 'Moraceae',
  Asparagus: 'Asparagaceae',
  Avena: 'Poaceae',
  Beta: 'Amaranthaceae',
  Brassica: 'Brassicaceae',
  Cajanus: 'Fabaceae',
  Camelina: 'Brassicaceae',
  Camellia: 'Theaceae',
  Canavalia: 'Fabaceae',
  Canna: 'Cannaceae',
  Cannabis: 'Cannabaceae',
  Capsicum: 'Solanaceae',
  Carica: 'Caricaceae',
  Carthamus: 'Asteraceae',
  Carya: 'Juglandaceae',
  Castanea: 'Fagaceae',
  Cenchrus: 'Poaceae',
  Chenopodium: 'Amaranthaceae',
  Cicer: 'Fabaceae',
  Cichorium: 'Asteraceae',
  Cinnamomum: 'Lauraceae',
  Citrullus: 'Cucurbitaceae',
  Citrus: 'Rutaceae',
  Cocos: 'Arecaceae',
  Coffea: 'Rubiaceae',
  Coix: 'Poaceae',
  Coleus: 'Lamiaceae',
  Colocasia: 'Araceae',
  Corchorus: 'Malvaceae',
  Coriandrum: 'Apiaceae',
  Corylus: 'Betulaceae',
  Crocus: 'Iridaceae',
  Cucumis: 'Cucurbitaceae',
  Cucurbita: 'Cucurbitaceae',
  Cuminum: 'Apiaceae',
  Curcuma: 'Zingiberaceae',
  Cyamopsis: 'Fabaceae',
  Cynara: 'Asteraceae',
  Daucus: 'Apiaceae',
  Digitaria: 'Poaceae',
  Dioscorea: 'Dioscoreaceae',
  Diospyros: 'Ebenaceae',
  Echinochloa: 'Poaceae',
  Elaeis: 'Arecaceae',
  Elettaria: 'Zingiberaceae',
  Eleusine: 'Poaceae',
  Eragrostis: 'Poaceae',
  Eriobotrya: 'Rosaceae',
  Eruca: 'Brassicaceae',
  Fagopyrum: 'Polygonaceae',
  Ficus: 'Moraceae',
  Foeniculum: 'Apiaceae',
  Fragaria: 'Rosaceae',
  Glycine: 'Fabaceae',
  Gossypium: 'Malvaceae',
  Guizotia: 'Asteraceae',
  Helianthus: 'Asteraceae',
  Hevea: 'Euphorbiaceae',
  Hordeum: 'Poaceae',
  Ipomoea: 'Convolvulaceae',
  Jatropha: 'Euphorbiaceae',
  Juglans: 'Juglandaceae',
  Lablab: 'Fabaceae',
  Lactuca: 'Asteraceae',
  Lathyrus: 'Fabaceae',
  Lavandula: 'Lamiaceae',
  Linum: 'Linaceae',
  Litchi: 'Sapindaceae',
  Lupinus: 'Fabaceae',
  Macadamia: 'Proteaceae',
  Macrotyloma: 'Fabaceae',
  Malus: 'Rosaceae',
  Mangifera: 'Anacardiaceae',
  Manihot: 'Euphorbiaceae',
  Maranta: 'Marantaceae',
  Matricaria: 'Asteraceae',
  Medicago: 'Fabaceae',
  Mentha: 'Lamiaceae',
  Mucuna: 'Fabaceae',
  Musa: 'Musaceae',
  Mutarda: 'Brassicaceae',
  Myristica: 'Myristicaceae',
  Nasturtium: 'Brassicaceae',
  Nicotiana: 'Solanaceae',
  Ocimum: 'Lamiaceae',
  Olea: 'Oleaceae',
  Origanum: 'Lamiaceae',
  Oryza: 'Poaceae',
  Oxalis: 'Oxalidaceae',
  Pachyrhizus: 'Fabaceae',
  Panicum: 'Poaceae',
  Paspalum: 'Poaceae',
  Passiflora: 'Passifloraceae',
  Perilla: 'Lamiaceae',
  Persea: 'Lauraceae',
  Petroselinum: 'Apiaceae',
  Phaseolus: 'Fabaceae',
  Phoenix: 'Arecaceae',
  Piper: 'Piperaceae',
  Pistacia: 'Anacardiaceae',
  Prunus: 'Rosaceae',
  Psidium: 'Myrtaceae',
  Psophocarpus: 'Fabaceae',
  Punica: 'Lythraceae',
  Pyrus: 'Rosaceae',
  Raphanus: 'Brassicaceae',
  Ribes: 'Grossulariaceae',
  Ricinus: 'Euphorbiaceae',
  Rubus: 'Rosaceae',
  Saccharum: 'Poaceae',
  Salvia: 'Lamiaceae',
  Secale: 'Poaceae',
  Selenicereus: 'Cactaceae',
  Sesamum: 'Pedaliaceae',
  Setaria: 'Poaceae',
  Simmondsia: 'Simmondsiaceae',
  Sinapis: 'Brassicaceae',
  Solanum: 'Solanaceae',
  Sorghum: 'Poaceae',
  Spinacia: 'Amaranthaceae',
  Syzygium: 'Myrtaceae',
  Tamarindus: 'Fabaceae',
  Theobroma: 'Malvaceae',
  Thymus: 'Lamiaceae',
  Triticum: 'Poaceae',
  Tropaeolum: 'Tropaeolaceae',
  Ullucus: 'Basellaceae',
  Vaccinium: 'Ericaceae',
  Vanilla: 'Orchidaceae',
  Vicia: 'Fabaceae',
  Vigna: 'Fabaceae',
  Vitis: 'Vitaceae',
  Xanthosoma: 'Araceae',
  Zea: 'Poaceae',
  Zingiber: 'Zingiberaceae',
  Zizania: 'Poaceae',
  x: 'Brassicaceae',
};

/**
 * Grain and fibre market classes, which are not botanical taxa.
 *
 * A market class describes how a harvest is graded and traded — by hardness,
 * colour, sowing season, staple length. It is not a plant. "Hard Red Winter" is
 * a wheat class; every wheat in it is Triticum aestivum, and a crop record
 * carrying the class as a common name asserts that a grading category is a
 * species.
 *
 * The corpus does not publish these as entities, so there is nothing to check a
 * name against — which is why they are pinned here. The list is not exhaustive
 * and does not need to be: it closes the named cases, and the duplicate-taxon
 * rule closes the rest, because a market class has no botanical name of its own
 * and can only enter by borrowing one that another identity already holds.
 */
export const MARKET_CLASS_NAMES: readonly string[] = [
  'hard red winter',
  'hard red spring',
  'soft red winter',
  'soft white',
  'hard white',
  'durum semolina',
  'no. 2 yellow',
  'yellow dent',
  'white dent',
  'flint corn',
  'upland cotton class',
  'pima class',
  'extra long staple',
  'long grain',
  'medium grain',
  'short grain',
  'malting barley',
  'feed barley',
  'food grade',
];
