import type { ImageMeta } from '@/types/content';

/**
 * Verified, self-hosted image registry keyed by `type:slug`.
 * Every entry was sourced from Wikimedia Commons and confirmed to carry a
 * redistribution-compatible license (CC0, Public domain, CC BY, or CC BY-SA)
 * with full attribution. Generated by scripts/fetch-images.mjs; do not hand-edit.
 */
export const IMAGE_MAP: Record<string, ImageMeta> = {
  'crop:wheat': {
    src: '/images/wheat.jpg',
    alt: 'A field of ripening wheat',
    width: 1280,
    height: 859,
    creator: 'Hugh Venables',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Ripe_wheat_field_-_geograph.org.uk_-_7835402.jpg/1280px-Ripe_wheat_field_-_geograph.org.uk_-_7835402.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:Ripe_wheat_field_-_geograph.org.uk_-_7835402.jpg',
    license: 'CC BY-SA 2.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.0',
    attribution: 'Hugh Venables, via Wikimedia Commons (CC BY-SA 2.0)',
    subject: 'ripe wheat field',
  },
  'crop:maize': {
    src: '/images/maize.jpg',
    alt: 'A field of maize (corn)',
    width: 1280,
    height: 720,
    creator: 'Sridhar Rao',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Early_corn_crop.jpg/1280px-Early_corn_crop.jpg',
    originalPage: 'https://commons.wikimedia.org/wiki/File:Early_corn_crop.jpg',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    attribution: 'Sridhar Rao, via Wikimedia Commons (CC BY-SA 4.0)',
    subject: 'maize corn field crop',
  },
  'crop:rice': {
    src: '/images/rice.jpg',
    alt: 'A flooded rice paddy field',
    width: 1280,
    height: 853,
    creator: 'Basile Morin',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Green_rice_sheaves_planted_in_a_paddy_field_with_long_shadows_at_golden_hour_in_Don_Det_Laos.jpg/1280px-Green_rice_sheaves_planted_in_a_paddy_field_with_long_shadows_at_golden_hour_in_Don_Det_Laos.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:Green_rice_sheaves_planted_in_a_paddy_field_with_long_shadows_at_golden_hour_in_Don_Det_Laos.jpg',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    attribution: 'Basile Morin, via Wikimedia Commons (CC BY-SA 4.0)',
    subject: 'rice paddy field',
  },
  'crop:soybean': {
    src: '/images/soybean.jpg',
    alt: 'A soybean field',
    width: 1280,
    height: 853,
    creator: 'USDAgov',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Mike_Starkey_Soybean_Harvest_%2852490323352%29.jpg/1280px-Mike_Starkey_Soybean_Harvest_%2852490323352%29.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:Mike_Starkey_Soybean_Harvest_(52490323352).jpg',
    license: 'Public domain',
    attribution: 'USDAgov, via Wikimedia Commons (Public domain)',
    subject: 'soybean field crop',
  },
  'crop:potato': {
    src: '/images/potato.jpg',
    alt: 'A field of potato plants',
    width: 1280,
    height: 834,
    creator: 'kallerna',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Perunapelto_Nakkila.JPG/1280px-Perunapelto_Nakkila.JPG',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:Perunapelto_Nakkila.JPG',
    license: 'CC BY-SA 3.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    attribution: 'kallerna, via Wikimedia Commons (CC BY-SA 3.0)',
    subject: 'potato plants field',
  },
  'crop:tomato': {
    src: '/images/tomato.jpg',
    alt: 'Ripe tomatoes on the plant',
    width: 1280,
    height: 1248,
    creator: 'Juan Carlos Fonseca Mata',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Maduraci%C3%B3n_del_tomate_%28Solanum_lycopersicum%29.jpg/1280px-Maduraci%C3%B3n_del_tomate_%28Solanum_lycopersicum%29.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:Maduraci%C3%B3n_del_tomate_(Solanum_lycopersicum).jpg',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    attribution:
      'Juan Carlos Fonseca Mata, via Wikimedia Commons (CC BY-SA 4.0)',
    subject: 'tomato plant fruit',
  },
  'crop:sunflower': {
    src: '/images/sunflower.jpg',
    alt: 'A field of sunflowers',
    width: 1280,
    height: 853,
    creator: 'Björn S.',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Sunflower_field_-_panoramio_%2811%29.jpg/1280px-Sunflower_field_-_panoramio_%2811%29.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:Sunflower_field_-_panoramio_(11).jpg',
    license: 'CC BY-SA 3.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    attribution: 'Björn S., via Wikimedia Commons (CC BY-SA 3.0)',
    subject: 'sunflower field',
  },
  'crop:barley': {
    src: '/images/barley.jpg',
    alt: 'A field of ripening barley',
    width: 1280,
    height: 1707,
    creator: 'Cassiville',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Barley_cover_crop_in_field.jpg/1280px-Barley_cover_crop_in_field.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:Barley_cover_crop_in_field.jpg',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    attribution: 'Cassiville, via Wikimedia Commons (CC BY-SA 4.0)',
    subject: 'barley field crop',
  },
  'crop:onion': {
    src: '/images/onion.jpg',
    alt: 'Onion plants in a field',
    width: 1280,
    height: 2041,
    creator: 'Burr, Fearing.',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/The_field_and_garden_vegetables_of_America_%28Page_140%29_%286002093135%29.jpg/1280px-The_field_and_garden_vegetables_of_America_%28Page_140%29_%286002093135%29.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:The_field_and_garden_vegetables_of_America_(Page_140)_(6002093135).jpg',
    license: 'Public domain',
    attribution: 'Burr, Fearing., via Wikimedia Commons (Public domain)',
    subject: 'onion bulb crop field',
  },
  'crop:carrot': {
    src: '/images/carrot.jpg',
    alt: 'Freshly harvested carrots',
    width: 1280,
    height: 1841,
    creator: 'Adimora chidinma',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Pile_of_Carrots.jpg/1280px-Pile_of_Carrots.jpg',
    originalPage: 'https://commons.wikimedia.org/wiki/File:Pile_of_Carrots.jpg',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    attribution: 'Adimora chidinma, via Wikimedia Commons (CC BY-SA 4.0)',
    subject: 'carrot roots harvest',
  },
  'crop:cabbage': {
    src: '/images/cabbage.jpg',
    alt: 'A field of cabbages',
    width: 1280,
    height: 721,
    creator: 'Jonathan Billinger',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Cabbage_crop_-_geograph.org.uk_-_7031529.jpg/1280px-Cabbage_crop_-_geograph.org.uk_-_7031529.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:Cabbage_crop_-_geograph.org.uk_-_7031529.jpg',
    license: 'CC BY-SA 2.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.0',
    attribution: 'Jonathan Billinger, via Wikimedia Commons (CC BY-SA 2.0)',
    subject: 'cabbage field crop',
  },
  'crop:lettuce': {
    src: '/images/lettuce.jpg',
    alt: 'Lettuce growing in a field',
    width: 1280,
    height: 1707,
    creator: 'HOWELLCREATIVE',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Crop_of_Baby_Butter_Lettuce%2C_in_Arroyo_Grande%2C_CA.jpg/1280px-Crop_of_Baby_Butter_Lettuce%2C_in_Arroyo_Grande%2C_CA.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:Crop_of_Baby_Butter_Lettuce,_in_Arroyo_Grande,_CA.jpg',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    attribution: 'HOWELLCREATIVE, via Wikimedia Commons (CC BY-SA 4.0)',
    subject: 'lettuce crop field',
  },
  'crop:cucumber': {
    src: '/images/cucumber.jpg',
    alt: 'Cucumbers growing on the vine',
    width: 1280,
    height: 850,
    creator: 'Nikodem Nijaki',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Greek_yoghurt_cucumbers_garlic.jpg/1280px-Greek_yoghurt_cucumbers_garlic.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:Greek_yoghurt_cucumbers_garlic.jpg',
    license: 'CC BY-SA 3.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    attribution: 'Nikodem Nijaki, via Wikimedia Commons (CC BY-SA 3.0)',
    subject: 'cucumber plant fruit',
  },
  'crop:sweet-pepper': {
    src: '/images/sweet-pepper.jpg',
    alt: 'Sweet (bell) peppers on the plant',
    width: 1280,
    height: 1015,
    creator: 'Wilfredor',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Capsicum_baccatum_in_Sa%C3%BAde_flea_market%2C_S%C3%A3o_Paulo%2C_Brazil.jpg/1280px-Capsicum_baccatum_in_Sa%C3%BAde_flea_market%2C_S%C3%A3o_Paulo%2C_Brazil.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:Capsicum_baccatum_in_Sa%C3%BAde_flea_market,_S%C3%A3o_Paulo,_Brazil.jpg',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    attribution: 'Wilfredor, via Wikimedia Commons (CC BY-SA 4.0)',
    subject: 'bell pepper plant capsicum',
  },
  'crop:spinach': {
    src: '/images/spinach.jpg',
    alt: 'Spinach leaves growing',
    width: 1280,
    height: 1707,
    creator: 'Adesolive',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Spinach_farming_in_Cameroon_%28Water_leave_gardening%29_01.jpg/1280px-Spinach_farming_in_Cameroon_%28Water_leave_gardening%29_01.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:Spinach_farming_in_Cameroon_(Water_leave_gardening)_01.jpg',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    attribution: 'Adesolive, via Wikimedia Commons (CC BY-SA 4.0)',
    subject: 'spinach leaves crop',
  },
  'crop:garlic': {
    src: '/images/garlic.jpg',
    alt: 'Harvested garlic bulbs',
    width: 1280,
    height: 853,
    creator: 'Matthew Pilachowski matthewpilachowski',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Garlic_Bulbs_%28Unsplash%29.jpg/1280px-Garlic_Bulbs_%28Unsplash%29.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:Garlic_Bulbs_(Unsplash).jpg',
    license: 'CC0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    attribution:
      'Matthew Pilachowski matthewpilachowski, via Wikimedia Commons (CC0)',
    subject: 'garlic bulbs harvest',
  },
  'crop:common-bean': {
    src: '/images/common-bean.jpg',
    alt: 'Common bean plants with pods',
    width: 1280,
    height: 1800,
    creator: 'Unknown authorUnknown author',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Haricot%2C_gousses_de_11_vari%C3%A9t%C3%A9s_Vilmorin-Andrieux_1904.png/1280px-Haricot%2C_gousses_de_11_vari%C3%A9t%C3%A9s_Vilmorin-Andrieux_1904.png',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:Haricot,_gousses_de_11_vari%C3%A9t%C3%A9s_Vilmorin-Andrieux_1904.png',
    license: 'Public domain',
    attribution:
      'Unknown authorUnknown author, via Wikimedia Commons (Public domain)',
    subject: 'common bean Phaseolus plant pods',
  },
  'crop:pea': {
    src: '/images/pea.jpg',
    alt: 'Pea pods on the plant',
    width: 1280,
    height: 1860,
    creator: 'Japanese fine prints, pre-1915',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Mame_-_pea_or_bean_plant_showing_vine%2C_leaves%2C_pods%2C_and_blossoms%29_-_Matsuwo%28%3F%29_LCCN2009630266.jpg/1280px-Mame_-_pea_or_bean_plant_showing_vine%2C_leaves%2C_pods%2C_and_blossoms%29_-_Matsuwo%28%3F%29_LCCN2009630266.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:Mame_-_pea_or_bean_plant_showing_vine,_leaves,_pods,_and_blossoms)_-_Matsuwo(%3F)_LCCN2009630266.jpg',
    license: 'Public domain',
    attribution:
      'Japanese fine prints, pre-1915, via Wikimedia Commons (Public domain)',
    subject: 'pea plant pods field',
  },
  'crop:chickpea': {
    src: '/images/chickpea.jpg',
    alt: 'Chickpea plants',
    width: 1280,
    height: 853,
    creator: 'Roger Culos',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Cicer_arietinum_noir_MHNT.BOT.2017.12.2.jpg/1280px-Cicer_arietinum_noir_MHNT.BOT.2017.12.2.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:Cicer_arietinum_noir_MHNT.BOT.2017.12.2.jpg',
    license: 'CC BY-SA 3.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    attribution: 'Roger Culos, via Wikimedia Commons (CC BY-SA 3.0)',
    subject: 'chickpea plant Cicer arietinum',
  },
  'crop:groundnut': {
    src: '/images/groundnut.jpg',
    alt: 'A groundnut (peanut) crop',
    width: 1280,
    height: 960,
    creator: 'Suglo20',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Groundnut_mill.jpg/1280px-Groundnut_mill.jpg',
    originalPage: 'https://commons.wikimedia.org/wiki/File:Groundnut_mill.jpg',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    attribution: 'Suglo20, via Wikimedia Commons (CC BY-SA 4.0)',
    subject: 'peanut groundnut plant Arachis',
  },
  'crop:apple': {
    src: '/images/apple.jpg',
    alt: 'Apples on a tree in an orchard',
    width: 1280,
    height: 853,
    creator: 'UnpetitproleX',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Orchards_in_snow%2C_Sangla%2C_Himachal_Pradesh%2C_India.jpg/1280px-Orchards_in_snow%2C_Sangla%2C_Himachal_Pradesh%2C_India.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:Orchards_in_snow,_Sangla,_Himachal_Pradesh,_India.jpg',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    attribution: 'UnpetitproleX, via Wikimedia Commons (CC BY-SA 4.0)',
    subject: 'apple orchard fruit tree',
  },
  'crop:grape': {
    src: '/images/grape.jpg',
    alt: 'Bunches of grapes in a vineyard',
    width: 1280,
    height: 854,
    creator: 'Ian Schneider on Unsplash',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/A_bunch_of_grapes_on_a_vine.jpg/1280px-A_bunch_of_grapes_on_a_vine.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:A_bunch_of_grapes_on_a_vine.jpg',
    license: 'CC0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    attribution: 'Ian Schneider on Unsplash, via Wikimedia Commons (CC0)',
    subject: 'grape vineyard bunches',
  },
  'crop:banana': {
    src: '/images/banana.jpg',
    alt: 'Bananas growing on a plant',
    width: 1280,
    height: 740,
    creator: 'Dr Benjamin F Place',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Banana_Plants%2C_Jamaica_6820807154.jpg/1280px-Banana_Plants%2C_Jamaica_6820807154.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:Banana_Plants,_Jamaica_6820807154.jpg',
    license: 'Public domain',
    attribution: 'Dr Benjamin F Place, via Wikimedia Commons (Public domain)',
    subject: 'banana plant fruit plantation',
  },
  'crop:orange': {
    src: '/images/orange.jpg',
    alt: 'Oranges on a citrus tree',
    width: 1280,
    height: 853,
    creator: 'Dietmar Rabich',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Orange_--_2022_--_9711.jpg/1280px-Orange_--_2022_--_9711.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:Orange_--_2022_--_9711.jpg',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    attribution: 'Dietmar Rabich, via Wikimedia Commons (CC BY-SA 4.0)',
    subject: 'orange citrus fruit tree',
  },
  'crop:mango': {
    src: '/images/mango.jpg',
    alt: 'Mangoes on a tree',
    width: 1280,
    height: 853,
    creator: 'Ivar Leidus',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Mangos_-_single_and_halved.jpg/1280px-Mangos_-_single_and_halved.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:Mangos_-_single_and_halved.jpg',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    attribution: 'Ivar Leidus, via Wikimedia Commons (CC BY-SA 4.0)',
    subject: 'mango fruit tree',
  },
  'crop:strawberry': {
    src: '/images/strawberry.jpg',
    alt: 'Strawberries growing on plants',
    width: 1280,
    height: 722,
    creator: 'Kenrick95',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Strawberry_plant%2C_Tongging%2C_Karo.jpg/1280px-Strawberry_plant%2C_Tongging%2C_Karo.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:Strawberry_plant,_Tongging,_Karo.jpg',
    license: 'CC BY-SA 3.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    attribution: 'Kenrick95, via Wikimedia Commons (CC BY-SA 3.0)',
    subject: 'strawberry plant fruit field',
  },
  'crop:cotton': {
    src: '/images/cotton.jpg',
    alt: 'A cotton field with open bolls',
    width: 1280,
    height: 853,
    creator: 'U.S. Department of Agriculture',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Cotton_harvester_at_sunset_with_dark_orange_sky_in_Batesville%2C_Texas_cotton_field.jpg/1280px-Cotton_harvester_at_sunset_with_dark_orange_sky_in_Batesville%2C_Texas_cotton_field.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:Cotton_harvester_at_sunset_with_dark_orange_sky_in_Batesville,_Texas_cotton_field.jpg',
    license: 'Public domain',
    attribution:
      'U.S. Department of Agriculture, via Wikimedia Commons (Public domain)',
    subject: 'cotton plant boll field',
  },
  'crop:alfalfa': {
    src: '/images/alfalfa.jpg',
    alt: 'An alfalfa (lucerne) field',
    width: 1280,
    height: 852,
    creator: 'Mahdikarimi70',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/%D9%85%D8%B2%D8%B1%D8%B9%D9%87_%DB%8C%D9%88%D9%86%D8%AC%D9%87_-Medicago_sativa_01.jpg/1280px-%D9%85%D8%B2%D8%B1%D8%B9%D9%87_%DB%8C%D9%88%D9%86%D8%AC%D9%87_-Medicago_sativa_01.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:%D9%85%D8%B2%D8%B1%D8%B9%D9%87_%DB%8C%D9%88%D9%86%D8%AC%D9%87_-Medicago_sativa_01.jpg',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    attribution: 'Mahdikarimi70, via Wikimedia Commons (CC BY-SA 4.0)',
    subject: 'alfalfa lucerne field crop',
  },
  'crop:sugarcane': {
    src: '/images/sugarcane.jpg',
    alt: 'A field of sugarcane',
    width: 1280,
    height: 720,
    creator: 'jared goss',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Sugarcane_crops_-_panoramio.jpg/1280px-Sugarcane_crops_-_panoramio.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:Sugarcane_crops_-_panoramio.jpg',
    license: 'CC BY-SA 3.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    attribution: 'jared goss, via Wikimedia Commons (CC BY-SA 3.0)',
    subject: 'sugarcane field crop',
  },
  'crop:sorghum': {
    src: '/images/sorghum.jpg',
    alt: 'A field of sorghum',
    width: 1280,
    height: 960,
    creator: 'ABHIJEET',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Sorghum_crop_Chinawal_04.jpg/1280px-Sorghum_crop_Chinawal_04.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:Sorghum_crop_Chinawal_04.jpg',
    license: 'CC BY-SA 3.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    attribution: 'ABHIJEET, via Wikimedia Commons (CC BY-SA 3.0)',
    subject: 'sorghum crop field',
  },
  'crop:oilseed-rape': {
    src: '/images/oilseed-rape.jpg',
    alt: 'A flowering oilseed rape (canola) field',
    width: 1280,
    height: 719,
    creator: 'Bernard Spragg. NZ from Christchurch, New Zealand',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Fields_of_Gold_%2852387403783%29.jpg/1280px-Fields_of_Gold_%2852387403783%29.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:Fields_of_Gold_(52387403783).jpg',
    license: 'Public domain',
    attribution:
      'Bernard Spragg. NZ from Christchurch, New Zealand, via Wikimedia Commons (Public domain)',
    subject: 'oilseed rape canola field flowering',
  },
  'crop:sugar-beet': {
    src: '/images/sugar-beet.jpg',
    alt: 'A sugar beet crop',
    width: 1280,
    height: 853,
    creator: 'Michael Garlick',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Happisburgh%2C_Sugar_beet_crop_-_geograph.org.uk_-_7805517.jpg/1280px-Happisburgh%2C_Sugar_beet_crop_-_geograph.org.uk_-_7805517.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:Happisburgh,_Sugar_beet_crop_-_geograph.org.uk_-_7805517.jpg',
    license: 'CC BY-SA 2.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.0',
    attribution: 'Michael Garlick, via Wikimedia Commons (CC BY-SA 2.0)',
    subject: 'sugar beet crop field',
  },
  'soil:clay-soil': {
    src: '/images/clay-soil.jpg',
    alt: 'Clay soil',
    width: 1280,
    height: 750,
    creator: 'Kaerii',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Soil_texture.png/1280px-Soil_texture.png',
    originalPage: 'https://commons.wikimedia.org/wiki/File:Soil_texture.png',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    attribution: 'Kaerii, via Wikimedia Commons (CC BY-SA 4.0)',
    subject: 'clay soil texture',
  },
  'soil:sandy-soil': {
    src: '/images/sandy-soil.jpg',
    alt: 'Sandy soil',
    width: 1280,
    height: 853,
    creator: 'PattayaPatrol',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/DFC_3926_A_cozy_cluster_of_fuzzy_and_spiky_cacti_in_small_pots_showcasing_a_variety_of_textures_and_green_hues.jpg/1280px-DFC_3926_A_cozy_cluster_of_fuzzy_and_spiky_cacti_in_small_pots_showcasing_a_variety_of_textures_and_green_hues.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:DFC_3926_A_cozy_cluster_of_fuzzy_and_spiky_cacti_in_small_pots_showcasing_a_variety_of_textures_and_green_hues.jpg',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    attribution: 'PattayaPatrol, via Wikimedia Commons (CC BY-SA 4.0)',
    subject: 'sandy soil texture',
  },
  'soil:loam-soil': {
    src: '/images/loam-soil.jpg',
    alt: 'Loam soil',
    width: 1280,
    height: 1950,
    creator:
      'Ella V. Baines (Firm); Henry G. Gilbert Nursery and Seed Trade Catalog Collection.',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Beautify_your_homes_%2816163976317%29.jpg/1280px-Beautify_your_homes_%2816163976317%29.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:Beautify_your_homes_(16163976317).jpg',
    license: 'Public domain',
    attribution:
      'Ella V. Baines (Firm); Henry G. Gilbert Nursery and Seed Trade Catalog Collection., via Wikimedia Commons (Public domain)',
    subject: 'loam soil texture hands',
  },
  'soil:silt-soil': {
    src: '/images/silt-soil.jpg',
    alt: 'Silt soil',
    width: 1280,
    height: 750,
    creator: 'Kaerii',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Soil_texture.png/1280px-Soil_texture.png',
    originalPage: 'https://commons.wikimedia.org/wiki/File:Soil_texture.png',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    attribution: 'Kaerii, via Wikimedia Commons (CC BY-SA 4.0)',
    subject: 'silt soil texture',
  },
  'soil:peat-soil': {
    src: '/images/peat-soil.jpg',
    alt: 'Dark peat soil',
    width: 1280,
    height: 960,
    creator: 'Nichole Ouellette',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Notre_Dame_du_Mont_Carmel_039.jpg/1280px-Notre_Dame_du_Mont_Carmel_039.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:Notre_Dame_du_Mont_Carmel_039.jpg',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    attribution: 'Nichole Ouellette, via Wikimedia Commons (CC BY-SA 4.0)',
    subject: 'peat soil bog',
  },
  'plant-disease:powdery-mildew': {
    src: '/images/powdery-mildew.jpg',
    alt: 'Powdery mildew on a leaf',
    width: 1280,
    height: 960,
    creator: 'Jerzy Opioła',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Powdery_Mildew_Acer_DK43_%281%29.jpg/1280px-Powdery_Mildew_Acer_DK43_%281%29.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:Powdery_Mildew_Acer_DK43_(1).jpg',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    attribution: 'Jerzy Opioła, via Wikimedia Commons (CC BY-SA 4.0)',
    subject: 'powdery mildew leaf disease',
  },
  'plant-disease:late-blight': {
    src: '/images/late-blight.jpg',
    alt: 'Late blight lesions on a leaf',
    width: 1280,
    height: 853,
    creator:
      'Mary Ann Hansen, Virginia Polytechnic Institute and State University, United States',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Phytophthora_infestans_on_potato_leaf.jpg/1280px-Phytophthora_infestans_on_potato_leaf.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:Phytophthora_infestans_on_potato_leaf.jpg',
    license: 'CC BY 3.0 us',
    licenseUrl: 'https://creativecommons.org/licenses/by/3.0/us/deed.en',
    attribution:
      'Mary Ann Hansen, Virginia Polytechnic Institute and State University, United States, via Wikimedia Commons (CC BY 3.0 us)',
    subject: 'late blight potato Phytophthora leaf',
  },
  'plant-disease:fusarium-wilt': {
    src: '/images/fusarium-wilt.jpg',
    alt: 'A plant affected by fusarium wilt',
    width: 1280,
    height: 854,
    creator: 'Plant pests and diseases',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Banana_%28Variety-_Koa_e_Kea%29-_Fusarium_wilt_%28Panama_disease%29_-_26445954078.jpg/1280px-Banana_%28Variety-_Koa_e_Kea%29-_Fusarium_wilt_%28Panama_disease%29_-_26445954078.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:Banana_(Variety-_Koa_e_Kea)-_Fusarium_wilt_(Panama_disease)_-_26445954078.jpg',
    license: 'CC0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    attribution: 'Plant pests and diseases, via Wikimedia Commons (CC0)',
    subject: 'fusarium wilt plant disease',
  },
  'plant-disease:root-rot': {
    src: '/images/root-rot.jpg',
    alt: 'Roots affected by rot',
    width: 1280,
    height: 2103,
    creator: 'Briggs, Lyman J.; United States.',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/The_field_treatment_of_tobacco_root-rot_BHL42610637.jpg/1280px-The_field_treatment_of_tobacco_root-rot_BHL42610637.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:The_field_treatment_of_tobacco_root-rot_BHL42610637.jpg',
    license: 'Public domain',
    attribution:
      'Briggs, Lyman J.; United States., via Wikimedia Commons (Public domain)',
    subject: 'root rot plant disease roots',
  },
  'plant-disease:wheat-leaf-rust': {
    src: '/images/wheat-leaf-rust.jpg',
    alt: 'Leaf rust pustules on wheat',
    width: 1280,
    height: 479,
    creator: 'Luis Fernández García',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Puccinia_graminis_20130828b.jpg/1280px-Puccinia_graminis_20130828b.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:Puccinia_graminis_20130828b.jpg',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    attribution: 'Luis Fernández García, via Wikimedia Commons (CC BY-SA 4.0)',
    subject: 'wheat leaf rust Puccinia',
  },
  'plant-disease:downy-mildew': {
    src: '/images/downy-mildew.jpg',
    alt: 'Downy mildew on a leaf',
    width: 913,
    height: 690,
    creator:
      'Dr. Jan Hinrichs-Berger, Landwirtschaftliches Technologiezentrum Augustenberg, Karlsruhe.',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/1/19/Salbei_%28Salvia_officinalis%29_mit_einem_Peronospora_salviae-officinalis_Befall_-_Hinrichs-Berger-2.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:Salbei_(Salvia_officinalis)_mit_einem_Peronospora_salviae-officinalis_Befall_-_Hinrichs-Berger-2.jpg',
    license: 'CC BY 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by/4.0',
    attribution:
      'Dr. Jan Hinrichs-Berger, Landwirtschaftliches Technologiezentrum Augustenberg, Karlsruhe., via Wikimedia Commons (CC BY 4.0)',
    subject: 'downy mildew leaf disease',
  },
  'plant-disease:gray-mold': {
    src: '/images/gray-mold.jpg',
    alt: 'Grey mould (Botrytis) on fruit',
    width: 1280,
    height: 960,
    creator: 'Schlaghecken Josef',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Himbeere_%28Rubus_idaeus%29_mit_Grauschimmel_%28Botrytis_cinerea%29-Josef_Schlaghecken.jpg/1280px-Himbeere_%28Rubus_idaeus%29_mit_Grauschimmel_%28Botrytis_cinerea%29-Josef_Schlaghecken.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:Himbeere_(Rubus_idaeus)_mit_Grauschimmel_(Botrytis_cinerea)-Josef_Schlaghecken.jpg',
    license: 'CC BY 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by/4.0',
    attribution: 'Schlaghecken Josef, via Wikimedia Commons (CC BY 4.0)',
    subject: 'botrytis grey mould fruit',
  },
  'plant-disease:anthracnose': {
    src: '/images/anthracnose.jpg',
    alt: 'Anthracnose lesions',
    width: 1280,
    height: 960,
    creator: 'Scot Nelson',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Mango_%28Mangifera_indica%29_Bacterial_black_spot_caused_by_Xanthomonas_citri_pv._mangiferae_indicae_%2840909388705%29.jpg/1280px-Mango_%28Mangifera_indica%29_Bacterial_black_spot_caused_by_Xanthomonas_citri_pv._mangiferae_indicae_%2840909388705%29.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:Mango_(Mangifera_indica)_Bacterial_black_spot_caused_by_Xanthomonas_citri_pv._mangiferae_indicae_(40909388705).jpg',
    license: 'CC0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    attribution: 'Scot Nelson, via Wikimedia Commons (CC0)',
    subject: 'anthracnose plant disease lesion',
  },
  'plant-disease:bacterial-leaf-spot': {
    src: '/images/bacterial-leaf-spot.jpg',
    alt: 'Bacterial leaf spots',
    width: 1280,
    height: 960,
    creator: 'Scot Nelson',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Hibiscus_Bacterial_leaf_spot_%2828018724659%29.jpg/1280px-Hibiscus_Bacterial_leaf_spot_%2828018724659%29.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:Hibiscus_Bacterial_leaf_spot_(28018724659).jpg',
    license: 'CC0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    attribution: 'Scot Nelson, via Wikimedia Commons (CC0)',
    subject: 'bacterial leaf spot plant disease',
  },
  'plant-disease:tobacco-mosaic-virus': {
    src: '/images/tobacco-mosaic-virus.jpg',
    alt: 'Mosaic virus symptoms on a leaf',
    width: 1280,
    height: 853,
    creator: 'R.J. Reynolds Tobacco Company Slide Set',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Tobacco_mosaic_virus_symptoms_tobacco.jpg/1280px-Tobacco_mosaic_virus_symptoms_tobacco.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:Tobacco_mosaic_virus_symptoms_tobacco.jpg',
    license: 'CC BY 3.0 us',
    licenseUrl: 'https://creativecommons.org/licenses/by/3.0/us/deed.en',
    attribution:
      'R.J. Reynolds Tobacco Company Slide Set, via Wikimedia Commons (CC BY 3.0 us)',
    subject: 'tobacco mosaic virus leaf symptoms',
  },
  'plant-disease:damping-off': {
    src: '/images/damping-off.jpg',
    alt: 'Seedlings affected by damping-off',
    width: 1280,
    height: 960,
    creator: 'peganum from Small Dole, England',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Seedlings_-_Flickr_-_peganum_%283%29.jpg/1280px-Seedlings_-_Flickr_-_peganum_%283%29.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:Seedlings_-_Flickr_-_peganum_(3).jpg',
    license: 'CC BY-SA 2.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.0',
    attribution:
      'peganum from Small Dole, England, via Wikimedia Commons (CC BY-SA 2.0)',
    subject: 'damping off seedling disease',
  },
  'pest:aphids': {
    src: '/images/aphids.jpg',
    alt: 'A colony of aphids on a plant',
    width: 1280,
    height: 853,
    creator: 'Brandon Antonio Segura Torres &amp; Priscilla Vieto Bonilla',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Pulgones_del_rosal_de_varios_colores.jpg/1280px-Pulgones_del_rosal_de_varios_colores.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:Pulgones_del_rosal_de_varios_colores.jpg',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    attribution:
      'Brandon Antonio Segura Torres &amp; Priscilla Vieto Bonilla, via Wikimedia Commons (CC BY-SA 4.0)',
    subject: 'aphids colony plant',
  },
  'pest:thrips': {
    src: '/images/thrips.jpg',
    alt: 'A thrips insect',
    width: 1280,
    height: 960,
    creator: 'Donald Hobern from Copenhagen, Denmark',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Thysanoptera_sp._%2825855771837%29.jpg/1280px-Thysanoptera_sp._%2825855771837%29.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:Thysanoptera_sp._(25855771837).jpg',
    license: 'CC BY 2.0',
    licenseUrl: 'https://creativecommons.org/licenses/by/2.0',
    attribution:
      'Donald Hobern from Copenhagen, Denmark, via Wikimedia Commons (CC BY 2.0)',
    subject: 'thrips insect Thysanoptera',
  },
  'pest:whiteflies': {
    src: '/images/whiteflies.jpg',
    alt: 'Whiteflies on the underside of a leaf',
    width: 1200,
    height: 1600,
    creator: 'Natalka Ukraine (baby-bear.org)',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/6/68/Iris_leaf_with_aphids_and_whiteflies_in_Dnipro_by_baby-bear.org.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:Iris_leaf_with_aphids_and_whiteflies_in_Dnipro_by_baby-bear.org.jpg',
    license: 'CC BY 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by/4.0',
    attribution:
      'Natalka Ukraine (baby-bear.org), via Wikimedia Commons (CC BY 4.0)',
    subject: 'whitefly insect Aleyrodidae leaf',
  },
  'pest:colorado-potato-beetle': {
    src: '/images/colorado-potato-beetle.jpg',
    alt: 'A Colorado potato beetle',
    width: 1280,
    height: 752,
    creator: 'Tavo Romann',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Colorado_potato_beetle_larvas_%28Leptinotarsa_decemlineata%29.jpg/1280px-Colorado_potato_beetle_larvas_%28Leptinotarsa_decemlineata%29.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:Colorado_potato_beetle_larvas_(Leptinotarsa_decemlineata).jpg',
    license: 'CC BY 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by/4.0',
    attribution: 'Tavo Romann, via Wikimedia Commons (CC BY 4.0)',
    subject: 'Colorado potato beetle Leptinotarsa',
  },
  'pest:fall-armyworm': {
    src: '/images/fall-armyworm.jpg',
    alt: 'A fall armyworm caterpillar',
    width: 1280,
    height: 1707,
    creator: 'Wee Hong',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Zea_mays_damaged_by_Spodoptera_frugiperda_%28200218-0814%29.jpg/1280px-Zea_mays_damaged_by_Spodoptera_frugiperda_%28200218-0814%29.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:Zea_mays_damaged_by_Spodoptera_frugiperda_(200218-0814).jpg',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    attribution: 'Wee Hong, via Wikimedia Commons (CC BY-SA 4.0)',
    subject: 'fall armyworm Spodoptera frugiperda larva',
  },
  'pest:european-corn-borer': {
    src: '/images/european-corn-borer.jpg',
    alt: 'A European corn borer',
    width: 1280,
    height: 1446,
    creator: 'Andy Reago &amp; Chrissy McClarren',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Ostrinia_nubilalis_%E2%80%93_European_Corn_Borer_Moth_%2814736403722%29.jpg/1280px-Ostrinia_nubilalis_%E2%80%93_European_Corn_Borer_Moth_%2814736403722%29.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:Ostrinia_nubilalis_%E2%80%93_European_Corn_Borer_Moth_(14736403722).jpg',
    license: 'CC BY 2.0',
    licenseUrl: 'https://creativecommons.org/licenses/by/2.0',
    attribution:
      'Andy Reago &amp; Chrissy McClarren, via Wikimedia Commons (CC BY 2.0)',
    subject: 'European corn borer Ostrinia',
  },
  'pest:wireworms': {
    src: '/images/wireworms.jpg',
    alt: 'A wireworm larva',
    width: 1280,
    height: 720,
    creator: 'Enno Merivee',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Pupae_of_the_parasitoid_Paracodrus_apterogynus.jpg/1280px-Pupae_of_the_parasitoid_Paracodrus_apterogynus.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:Pupae_of_the_parasitoid_Paracodrus_apterogynus.jpg',
    license: 'CC0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    attribution: 'Enno Merivee, via Wikimedia Commons (CC0)',
    subject: 'wireworm click beetle larva soil',
  },
  'pest:cutworms': {
    src: '/images/cutworms.jpg',
    alt: 'A cutworm caterpillar',
    width: 1280,
    height: 1707,
    creator: 'Jeevan Jose, Kerala, India',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Noctuidae_at_Kadavoor.jpg/1280px-Noctuidae_at_Kadavoor.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:Noctuidae_at_Kadavoor.jpg',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    attribution:
      'Jeevan Jose, Kerala, India, via Wikimedia Commons (CC BY-SA 4.0)',
    subject: 'cutworm caterpillar soil',
  },
  'pest:desert-locust': {
    src: '/images/desert-locust.jpg',
    alt: 'A desert locust',
    width: 1280,
    height: 498,
    creator: 'Adam Matan',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Desert_Locust_swarm_in_desert_scenery.jpg/1280px-Desert_Locust_swarm_in_desert_scenery.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:Desert_Locust_swarm_in_desert_scenery.jpg',
    license: 'CC BY-SA 3.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    attribution: 'Adam Matan, via Wikimedia Commons (CC BY-SA 3.0)',
    subject: 'desert locust Schistocerca swarm',
  },
  'pest:codling-moth': {
    src: '/images/codling-moth.jpg',
    alt: 'A codling moth',
    width: 1280,
    height: 960,
    creator: 'Patrick Clement from West Midlands, England',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/49.338_BF1261_Codling_Moth%2C_Cydia_pomonella_%28larval_damage_to_apples%29_%283852049334%29.jpg/1280px-49.338_BF1261_Codling_Moth%2C_Cydia_pomonella_%28larval_damage_to_apples%29_%283852049334%29.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:49.338_BF1261_Codling_Moth,_Cydia_pomonella_(larval_damage_to_apples)_(3852049334).jpg',
    license: 'CC BY 2.0',
    licenseUrl: 'https://creativecommons.org/licenses/by/2.0',
    attribution:
      'Patrick Clement from West Midlands, England, via Wikimedia Commons (CC BY 2.0)',
    subject: 'codling moth Cydia pomonella apple',
  },
  'pest:leaf-miners': {
    src: '/images/leaf-miners.jpg',
    alt: 'Leaf miner tunnels in a leaf',
    width: 1280,
    height: 960,
    creator: 'Forest and Kim Starr',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Starr-180305-0585-Bidens_pilosa-leaf_miner_damage_on_leaves-Kahikinui-Maui_%2841192896632%29.jpg/1280px-Starr-180305-0585-Bidens_pilosa-leaf_miner_damage_on_leaves-Kahikinui-Maui_%2841192896632%29.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:Starr-180305-0585-Bidens_pilosa-leaf_miner_damage_on_leaves-Kahikinui-Maui_(41192896632).jpg',
    license: 'CC BY 3.0 us',
    licenseUrl: 'https://creativecommons.org/licenses/by/3.0/us/deed.en',
    attribution: 'Forest and Kim Starr, via Wikimedia Commons (CC BY 3.0 us)',
    subject: 'leaf miner damage mine leaf',
  },
  'pest:root-knot-nematode': {
    src: '/images/root-knot-nematode.jpg',
    alt: 'Root-knot nematode galls on roots',
    width: 1280,
    height: 1560,
    creator:
      'Photo by William Wergin and Richard Sayre. Colorized by Stephen Ausmus. U.S. Department of Agriculture',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/A_juvenile_root-knot_nematode_%28Meloidogyne_incognita%29_penetrates_a_tomato_root_-_USDA-ARS.jpg/1280px-A_juvenile_root-knot_nematode_%28Meloidogyne_incognita%29_penetrates_a_tomato_root_-_USDA-ARS.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:A_juvenile_root-knot_nematode_(Meloidogyne_incognita)_penetrates_a_tomato_root_-_USDA-ARS.jpg',
    license: 'CC BY 2.0',
    licenseUrl: 'https://creativecommons.org/licenses/by/2.0',
    attribution:
      'Photo by William Wergin and Richard Sayre. Colorized by Stephen Ausmus. U.S. Department of Agriculture, via Wikimedia Commons (CC BY 2.0)',
    subject: 'root knot nematode galls roots Meloidogyne',
  },
  'pest:slugs': {
    src: '/images/slugs.jpg',
    alt: 'A slug on a plant',
    width: 1280,
    height: 720,
    creator: 'Dandy1022',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Portuguese_squill.jpg/1280px-Portuguese_squill.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:Portuguese_squill.jpg',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    attribution: 'Dandy1022, via Wikimedia Commons (CC BY-SA 4.0)',
    subject: 'slug garden pest plant',
  },
  'livestock:cattle': {
    src: '/images/cattle.jpg',
    alt: 'Cattle grazing in a pasture',
    width: 1280,
    height: 852,
    creator: 'Martin Abegglen',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Dairy_cows_on_pasture_in_Ireland.jpg/1280px-Dairy_cows_on_pasture_in_Ireland.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:Dairy_cows_on_pasture_in_Ireland.jpg',
    license: 'CC BY-SA 2.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.0',
    attribution: 'Martin Abegglen, via Wikimedia Commons (CC BY-SA 2.0)',
    subject: 'dairy cattle cows pasture',
  },
  'livestock:sheep': {
    src: '/images/sheep.jpg',
    alt: 'A flock of sheep',
    width: 1280,
    height: 853,
    creator: 'Zeynel Cebeci',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Sheep_flock_in_grasland_in_E%C4%9Fribel_01.jpg/1280px-Sheep_flock_in_grasland_in_E%C4%9Fribel_01.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:Sheep_flock_in_grasland_in_E%C4%9Fribel_01.jpg',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    attribution: 'Zeynel Cebeci, via Wikimedia Commons (CC BY-SA 4.0)',
    subject: 'sheep flock pasture',
  },
  'livestock:goats': {
    src: '/images/goats.jpg',
    alt: 'Goats on a farm',
    width: 1280,
    height: 980,
    creator: 'Lisbeth Bergh',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/ANSK_11295_14269x10922_LISBETH_BERGH_Norske_anskuelsesbilleder_NORWAY_1914_S%C3%86TER_%28seter_summer_pasture_mountain_farm_dairy_milkmaids_log_cabins_cows_sheep_goat%29_skoleplansje_%28school_wall_chart%29_Det_Kgl._Bibliotek_No_copyright.jpg/1280px-thumbnail.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:ANSK_11295_14269x10922_LISBETH_BERGH_Norske_anskuelsesbilleder_NORWAY_1914_S%C3%86TER_(seter_summer_pasture_mountain_farm_dairy_milkmaids_log_cabins_cows_sheep_goat)_skoleplansje_(school_wall_chart)_Det_Kgl._Bibliotek_No_copyright.jpg',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    attribution: 'Lisbeth Bergh, via Wikimedia Commons (CC BY-SA 4.0)',
    subject: 'goats farm pasture',
  },
  'livestock:pigs': {
    src: '/images/pigs.jpg',
    alt: 'Domestic pigs',
    width: 1280,
    height: 766,
    creator: 'Tim Green',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/2016_Norland_Scarecrow_Festival_12.jpg/1280px-2016_Norland_Scarecrow_Festival_12.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:2016_Norland_Scarecrow_Festival_12.jpg',
    license: 'CC BY 2.0',
    licenseUrl: 'https://creativecommons.org/licenses/by/2.0',
    attribution: 'Tim Green, via Wikimedia Commons (CC BY 2.0)',
    subject: 'pigs farm domestic',
  },
  'livestock:chickens': {
    src: '/images/chickens.jpg',
    alt: 'Chickens on a farm',
    width: 1280,
    height: 960,
    creator: 'State Government Photographer',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Hen_at_Parafield_Poultry_Farm%28GN09712%29.jpg/1280px-Hen_at_Parafield_Poultry_Farm%28GN09712%29.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:Hen_at_Parafield_Poultry_Farm(GN09712).jpg',
    license: 'CC0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    attribution: 'State Government Photographer, via Wikimedia Commons (CC0)',
    subject: 'chickens hens poultry farm',
  },
  'livestock:horses': {
    src: '/images/horses.jpg',
    alt: 'A horse in a pasture',
    width: 1280,
    height: 960,
    creator: 'EgorovaSvetlana',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Brown_Horse_Pasture_Undermountain_Home_Farm_Equestrian_Center.jpg/1280px-Brown_Horse_Pasture_Undermountain_Home_Farm_Equestrian_Center.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:Brown_Horse_Pasture_Undermountain_Home_Farm_Equestrian_Center.jpg',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    attribution: 'EgorovaSvetlana, via Wikimedia Commons (CC BY-SA 4.0)',
    subject: 'horse farm pasture',
  },
  'livestock:honey-bees': {
    src: '/images/honey-bees.jpg',
    alt: 'Honey bees on a frame',
    width: 1280,
    height: 1707,
    creator: 'Queenzlander',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/OATH_Bee_Hive.jpg/1280px-OATH_Bee_Hive.jpg',
    originalPage: 'https://commons.wikimedia.org/wiki/File:OATH_Bee_Hive.jpg',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    attribution: 'Queenzlander, via Wikimedia Commons (CC BY-SA 4.0)',
    subject: 'honey bee hive apiary',
  },
  'livestock:farmed-fish': {
    src: '/images/farmed-fish.jpg',
    alt: 'A fish farm (aquaculture)',
    width: 1280,
    height: 853,
    creator: 'Sophia Guevara',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Foto_Keramba_Ikan_%28Panatapan%2C_Parapat%2C_Simalungun%29.jpg/1280px-Foto_Keramba_Ikan_%28Panatapan%2C_Parapat%2C_Simalungun%29.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:Foto_Keramba_Ikan_(Panatapan,_Parapat,_Simalungun).jpg',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    attribution: 'Sophia Guevara, via Wikimedia Commons (CC BY-SA 4.0)',
    subject: 'aquaculture fish farm cages',
  },
  'livestock:turkeys': {
    src: '/images/turkeys.jpg',
    alt: 'Domestic turkeys',
    width: 1280,
    height: 853,
    creator: 'USDAgov',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/20181031-AMS-PJK-0298_TONED.jpg/1280px-20181031-AMS-PJK-0298_TONED.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:20181031-AMS-PJK-0298_TONED.jpg',
    license: 'Public domain',
    attribution: 'USDAgov, via Wikimedia Commons (Public domain)',
    subject: 'turkey poultry farm domestic',
  },
  'machinery:tractor': {
    src: '/images/tractor.jpg',
    alt: 'A tractor working in a field',
    width: 1280,
    height: 720,
    creator: 'W.carter',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Silage_windrows_and_two_tractors_2.jpg/1280px-Silage_windrows_and_two_tractors_2.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:Silage_windrows_and_two_tractors_2.jpg',
    license: 'CC0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    attribution: 'W.carter, via Wikimedia Commons (CC0)',
    subject: 'farm tractor field',
  },
  'machinery:combine-harvester': {
    src: '/images/combine-harvester.jpg',
    alt: 'A combine harvester at work',
    width: 1280,
    height: 1185,
    creator: 'FOTO:Fortepan — ID 89614: Adományozó/Donor: Urbán Tamás.',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Harvest%2C_agriculture%2C_grain%2C_wheat-field%2C_combine_harvester_Fortepan_89614.jpg/1280px-Harvest%2C_agriculture%2C_grain%2C_wheat-field%2C_combine_harvester_Fortepan_89614.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:Harvest,_agriculture,_grain,_wheat-field,_combine_harvester_Fortepan_89614.jpg',
    license: 'CC BY-SA 3.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    attribution:
      'FOTO:Fortepan — ID 89614: Adományozó/Donor: Urbán Tamás., via Wikimedia Commons (CC BY-SA 3.0)',
    subject: 'combine harvester wheat field',
  },
  'machinery:seed-drill': {
    src: '/images/seed-drill.jpg',
    alt: 'A seed drill',
    width: 1280,
    height: 837,
    creator: 'Joost J. Bakker from IJmuiden',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Fiat_Tractor_%2C_Fiat_500_DT.jpg/1280px-Fiat_Tractor_%2C_Fiat_500_DT.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:Fiat_Tractor_,_Fiat_500_DT.jpg',
    license: 'CC BY 2.0',
    licenseUrl: 'https://creativecommons.org/licenses/by/2.0',
    attribution:
      'Joost J. Bakker from IJmuiden, via Wikimedia Commons (CC BY 2.0)',
    subject: 'seed drill planter tractor',
  },
  'machinery:sprayer': {
    src: '/images/sprayer.jpg',
    alt: 'A boom sprayer in a field',
    width: 1280,
    height: 853,
    creator: 'USDAgov',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Secretary_Vilsack_at_Farm_Progress_Show_%2820220831-OSEC-LSC-0237%29.jpg/1280px-Secretary_Vilsack_at_Farm_Progress_Show_%2820220831-OSEC-LSC-0237%29.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:Secretary_Vilsack_at_Farm_Progress_Show_(20220831-OSEC-LSC-0237).jpg',
    license: 'Public domain',
    attribution: 'USDAgov, via Wikimedia Commons (Public domain)',
    subject: 'agricultural sprayer boom field',
  },
  'machinery:disc-harrow': {
    src: '/images/disc-harrow.jpg',
    alt: 'A disc harrow',
    width: 1280,
    height: 1751,
    creator:
      'Henry G. Gilbert Nursery and Seed Trade Catalog Collection.; J. Manns &amp; Co.',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Manns%27_superior_seeds_%2815767635494%29.jpg/1280px-Manns%27_superior_seeds_%2815767635494%29.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:Manns%27_superior_seeds_(15767635494).jpg',
    license: 'CC BY 2.0',
    licenseUrl: 'https://creativecommons.org/licenses/by/2.0',
    attribution:
      'Henry G. Gilbert Nursery and Seed Trade Catalog Collection.; J. Manns &amp; Co., via Wikimedia Commons (CC BY 2.0)',
    subject: 'disc harrow field cultivation',
  },
  'machinery:baler': {
    src: '/images/baler.jpg',
    alt: 'A baler making bales',
    width: 1280,
    height: 853,
    creator: 'DimiTalen',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Round_hay_bales_on_a_field%2C_with_hawkweed_in_the_foreground%2C_near_Durnal%2C_Yvoir%2C_2025.jpg/1280px-Round_hay_bales_on_a_field%2C_with_hawkweed_in_the_foreground%2C_near_Durnal%2C_Yvoir%2C_2025.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:Round_hay_bales_on_a_field,_with_hawkweed_in_the_foreground,_near_Durnal,_Yvoir,_2025.jpg',
    license: 'CC0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    attribution: 'DimiTalen, via Wikimedia Commons (CC0)',
    subject: 'round baler hay bales field',
  },
  'machinery:rotary-mower': {
    src: '/images/rotary-mower.jpg',
    alt: 'A mower cutting a field',
    width: 1280,
    height: 1648,
    creator:
      'Henry G. Gilbert Nursery and Seed Trade Catalog Collection.; Peter Henderson &amp; Co.',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Everything_for_the_garden_%2816666934450%29.jpg/1280px-Everything_for_the_garden_%2816666934450%29.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:Everything_for_the_garden_(16666934450).jpg',
    license: 'Public domain',
    attribution:
      'Henry G. Gilbert Nursery and Seed Trade Catalog Collection.; Peter Henderson &amp; Co., via Wikimedia Commons (Public domain)',
    subject: 'agricultural mower cutting grass field',
  },
  'machinery:agricultural-drone': {
    src: '/images/agricultural-drone.jpg',
    alt: 'An agricultural drone over a field',
    width: 1280,
    height: 854,
    creator: 'Shreesha Sharma',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Agricultural_drone_spraying_on_paddy_field.jpg/1280px-Agricultural_drone_spraying_on_paddy_field.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:Agricultural_drone_spraying_on_paddy_field.jpg',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    attribution: 'Shreesha Sharma, via Wikimedia Commons (CC BY-SA 4.0)',
    subject: 'agricultural drone spraying field',
  },
  'fertilizer:compost': {
    src: '/images/compost.jpg',
    alt: 'A compost heap',
    width: 1280,
    height: 960,
    creator: 'SuSanA Secretariat',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Outdoor_UDDT_%285881121810%29.jpg/1280px-Outdoor_UDDT_%285881121810%29.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:Outdoor_UDDT_(5881121810).jpg',
    license: 'CC BY 2.0',
    licenseUrl: 'https://creativecommons.org/licenses/by/2.0',
    attribution: 'SuSanA Secretariat, via Wikimedia Commons (CC BY 2.0)',
    subject: 'compost heap organic matter',
  },
  'fertilizer:farmyard-manure': {
    src: '/images/farmyard-manure.jpg',
    alt: 'A heap of farmyard manure',
    width: 1280,
    height: 852,
    creator: 'Simon Mortimer',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Farmyard_manure_heap_near_Crug-Glas_Farm_-_geograph.org.uk_-_5657274.jpg/1280px-Farmyard_manure_heap_near_Crug-Glas_Farm_-_geograph.org.uk_-_5657274.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:Farmyard_manure_heap_near_Crug-Glas_Farm_-_geograph.org.uk_-_5657274.jpg',
    license: 'CC BY-SA 2.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.0',
    attribution: 'Simon Mortimer, via Wikimedia Commons (CC BY-SA 2.0)',
    subject: 'farmyard manure heap',
  },
  'fertilizer:vermicompost': {
    src: '/images/vermicompost.jpg',
    alt: 'Vermicompost',
    width: 1280,
    height: 853,
    creator: 'Matthew.kowal',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Maintaining_a_5_gallon_vermicompost_bucket_that_is_buried_in_a_plot_at_the_Garfield_Neighborhood_Garden_in_Phoenix%2C_Arizona.jpg/1280px-Maintaining_a_5_gallon_vermicompost_bucket_that_is_buried_in_a_plot_at_the_Garfield_Neighborhood_Garden_in_Phoenix%2C_Arizona.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:Maintaining_a_5_gallon_vermicompost_bucket_that_is_buried_in_a_plot_at_the_Garfield_Neighborhood_Garden_in_Phoenix,_Arizona.jpg',
    license: 'CC BY 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by/4.0',
    attribution: 'Matthew.kowal, via Wikimedia Commons (CC BY 4.0)',
    subject: 'vermicompost worms castings',
  },
  'irrigation-method:drip-irrigation': {
    src: '/images/drip-irrigation.jpg',
    alt: 'A drip irrigation line watering plants',
    width: 1280,
    height: 670,
    creator: 'USDAgov',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/20150415-USDA-OC-PSD-0068_Agriculture_in_the_United_States.jpg/1280px-20150415-USDA-OC-PSD-0068_Agriculture_in_the_United_States.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:20150415-USDA-OC-PSD-0068_Agriculture_in_the_United_States.jpg',
    license: 'Public domain',
    attribution: 'USDAgov, via Wikimedia Commons (Public domain)',
    subject: 'drip irrigation emitter crop',
  },
  'irrigation-method:sprinkler-irrigation': {
    src: '/images/sprinkler-irrigation.jpg',
    alt: 'Sprinkler irrigation in a field',
    width: 1280,
    height: 853,
    creator: 'User: Vraj Acharya, WELL Labs',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Sprinkler_head_in_a_cultivated_field_in_Raichur.jpg/1280px-Sprinkler_head_in_a_cultivated_field_in_Raichur.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:Sprinkler_head_in_a_cultivated_field_in_Raichur.jpg',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    attribution:
      'User: Vraj Acharya, WELL Labs, via Wikimedia Commons (CC BY-SA 4.0)',
    subject: 'sprinkler irrigation field water',
  },
  'irrigation-method:center-pivot-irrigation': {
    src: '/images/center-pivot-irrigation.jpg',
    alt: 'A center-pivot irrigation system',
    width: 1280,
    height: 1220,
    creator:
      'NASA, crew of STS-80 Space Shuttle Columbia mission, one of Kenneth D. Cockrell, Kent Rominger, Story Musgrave, Thomas David Jones, Tamara E. Jernigan',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Kuwait_city_1996.jpg/1280px-Kuwait_city_1996.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:Kuwait_city_1996.jpg',
    license: 'Public domain',
    attribution:
      'NASA, crew of STS-80 Space Shuttle Columbia mission, one of Kenneth D. Cockrell, Kent Rominger, Story Musgrave, Thomas David Jones, Tamara E. Jernigan, via Wikimedia Commons (Public domain)',
    subject: 'center pivot irrigation aerial field',
  },
  'irrigation-method:furrow-irrigation': {
    src: '/images/furrow-irrigation.jpg',
    alt: 'Furrow irrigation between crop rows',
    width: 1280,
    height: 855,
    creator: 'LBM1948',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Estado_Shan%2C_varios_05.jpg/1280px-Estado_Shan%2C_varios_05.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:Estado_Shan,_varios_05.jpg',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    attribution: 'LBM1948, via Wikimedia Commons (CC BY-SA 4.0)',
    subject: 'furrow irrigation field water',
  },
  'irrigation-method:surface-irrigation': {
    src: '/images/surface-irrigation.jpg',
    alt: 'Surface (flood) irrigation of a field',
    width: 1280,
    height: 854,
    creator: 'USDAgov',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Irrigation_and_Water_%2820150828-NRCS-LSC-0021%29.jpg/1280px-Irrigation_and_Water_%2820150828-NRCS-LSC-0021%29.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:Irrigation_and_Water_(20150828-NRCS-LSC-0021).jpg',
    license: 'Public domain',
    attribution: 'USDAgov, via Wikimedia Commons (Public domain)',
    subject: 'flood surface irrigation field',
  },
  'farming-system:organic-farming': {
    src: '/images/organic-farming.jpg',
    alt: 'An organic vegetable farm',
    width: 1280,
    height: 854,
    creator: 'Simon Mortimer',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Organic_vegetable_cultivation_at_Easthill_Farm_-_geograph.org.uk_-_6531132.jpg/1280px-Organic_vegetable_cultivation_at_Easthill_Farm_-_geograph.org.uk_-_6531132.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:Organic_vegetable_cultivation_at_Easthill_Farm_-_geograph.org.uk_-_6531132.jpg',
    license: 'CC BY-SA 2.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.0',
    attribution: 'Simon Mortimer, via Wikimedia Commons (CC BY-SA 2.0)',
    subject: 'organic farm vegetables field',
  },
  'farming-system:greenhouse-farming': {
    src: '/images/greenhouse-farming.jpg',
    alt: 'Crops growing in a greenhouse',
    width: 1280,
    height: 720,
    creator:
      'U.S. Department of Agriculture Lance Cheung/Multimedia PhotoJournalist',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Farm_workers_pick_strawberries_in_in_Fort_Valley%2C_GA_20190507-OSEC-LSC-0744_%2840898326723%29.jpg/1280px-Farm_workers_pick_strawberries_in_in_Fort_Valley%2C_GA_20190507-OSEC-LSC-0744_%2840898326723%29.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:Farm_workers_pick_strawberries_in_in_Fort_Valley,_GA_20190507-OSEC-LSC-0744_(40898326723).jpg',
    license: 'Public domain',
    attribution:
      'U.S. Department of Agriculture Lance Cheung/Multimedia PhotoJournalist, via Wikimedia Commons (Public domain)',
    subject: 'greenhouse crop production tomatoes',
  },
  'farming-system:agroforestry': {
    src: '/images/agroforestry.jpg',
    alt: 'Trees integrated with crops (agroforestry)',
    width: 1280,
    height: 960,
    creator: 'National Agroforestry Center',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Pine_and_cotton_alley_cropping_%2826168344991%29.jpg/1280px-Pine_and_cotton_alley_cropping_%2826168344991%29.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:Pine_and_cotton_alley_cropping_(26168344991).jpg',
    license: 'CC BY 2.0',
    licenseUrl: 'https://creativecommons.org/licenses/by/2.0',
    attribution:
      'National Agroforestry Center, via Wikimedia Commons (CC BY 2.0)',
    subject: 'agroforestry trees crops field',
  },
  'climate:drought': {
    src: '/images/drought.jpg',
    alt: 'Cracked, drought-affected soil',
    width: 1280,
    height: 853,
    creator: 'Andrew Cattoir (Lake Mead National Recreation Area)',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Dry_Cracked_Mud_%284957b8b2-f52c-43b0-acc2-ead42cf6f03b%29.jpg/1280px-Dry_Cracked_Mud_%284957b8b2-f52c-43b0-acc2-ead42cf6f03b%29.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:Dry_Cracked_Mud_(4957b8b2-f52c-43b0-acc2-ead42cf6f03b).jpg',
    license: 'Public domain',
    attribution:
      'Andrew Cattoir (Lake Mead National Recreation Area), via Wikimedia Commons (Public domain)',
    subject: 'drought cracked dry soil field',
  },
  'climate:frost': {
    src: '/images/frost.jpg',
    alt: 'Frost on a crop',
    width: 1280,
    height: 853,
    creator: 'Dietmar Rabich',
    sourceUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/D%C3%BClmen%2C_Hausd%C3%BClmen%2C_Eiskristalle_auf_Bl%C3%A4ttern_--_2022_--_9657.jpg/1280px-D%C3%BClmen%2C_Hausd%C3%BClmen%2C_Eiskristalle_auf_Bl%C3%A4ttern_--_2022_--_9657.jpg',
    originalPage:
      'https://commons.wikimedia.org/wiki/File:D%C3%BClmen,_Hausd%C3%BClmen,_Eiskristalle_auf_Bl%C3%A4ttern_--_2022_--_9657.jpg',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    attribution: 'Dietmar Rabich, via Wikimedia Commons (CC BY-SA 4.0)',
    subject: 'frost crop plant leaves ice',
  },
};
