import type { CommodityProductContent } from '@/types/content';

export const dehydratedOnion: CommodityProductContent = {
  id: 'commodity-product-dehydrated-onion',
  slug: 'dehydrated-onion',
  contentType: 'commodity-product',
  title: 'Dehydrated Onion',
  alternativeNames: [
    'Dried onion',
    'Onion flakes',
    'Onion granules',
    'Onion powder',
  ],
  category: 'Primary processed product',
  subcategory: 'Dehydrated vegetable',
  productClass: 'primary-product',
  derivedFrom: { type: 'commodity', slug: 'dry-bulb-onions' },
  producedBy: [{ type: 'processing-method', slug: 'vegetable-dehydration' }],
  physicalForm: 'other',
  summary:
    'Dehydrated onion is the primary product of onion dehydration: bulbs peeled, sliced, and dried until the water that makes a fresh onion perishable is gone, then traded as flakes, granules, or powder for food manufacturing.',
  introduction: [
    {
      type: 'paragraph',
      text: 'Dehydrated onion is what an onion dehydration plant is run to produce. Cured bulbs are topped, tailed, peeled, sliced, and dried in stages until almost all of their water has been removed, then sized into the traded formats — flakes, chopped or minced grades, granules, and powder. The shift is fundamental rather than one of degree: a fresh onion is a living tissue with a shelf life measured in months, while dehydrated onion is a dry ingredient measured in years.',
    },
    {
      type: 'paragraph',
      text: 'It is an ingredient rather than a food in its own right. The bulk of it is bought by food manufacturers, who use it where onion flavour is wanted without the weight, waste, labour, and perishability of the fresh bulb. That trade-off — flavour retained, water and handling costs removed — is the entire commercial logic of the product.',
    },
  ],
  keyFacts: [
    { label: 'Product class', value: 'Primary product of onion dehydration' },
    { label: 'Made from', value: 'Cured dry bulb onions (Allium cepa)' },
    {
      label: 'Defining operation',
      value: 'Staged drying to remove nearly all water',
    },
    {
      label: 'Traded formats',
      value: 'Flakes, chopped and minced grades, granules, and powder',
    },
    {
      label: 'Raw-material driver',
      value: 'High-solids, high-pungency cultivars grown for dehydration',
    },
    { label: 'Principal use', value: 'Food manufacturing ingredient' },
  ],
  sections: [
    {
      id: 'raw-material',
      heading: 'A different onion goes into it',
      body: [
        {
          type: 'paragraph',
          text: 'Dehydrators do not buy the onions that supermarkets buy. The economics of drying are dominated by how much water has to be evaporated, so the industry uses cultivars bred for high solids content and grown specifically for the purpose — typically white, strongly pungent onions rather than the mild sweet types prized for fresh eating. More solids per bulb means more product per tonne delivered and less energy spent boiling off water.',
        },
        {
          type: 'callout',
          tone: 'note',
          title: 'The mild onion is the wrong onion here',
          text: 'Sweet, mild onions are a premium fresh-market commodity and a poor dehydration raw material: low in solids and low in the pungency that carries through drying. Fresh-market desirability and dehydration suitability point in opposite directions.',
        },
      ],
    },
    {
      id: 'processing',
      heading: 'From bulb to flake',
      body: [
        {
          type: 'paragraph',
          text: 'Bulbs are topped and tailed, peeled, inspected, and sliced, then dried on moving belts through successive stages, each drier than the last — the bulk of the water leaves early and quickly, while the last of it is removed slowly and gently, because that final stage is where heat damage and browning happen. Dried slices are then broken and screened into size grades, with powder produced by milling. Flakes, granules, and powder are the same dried material differentiated by particle size, so a single line yields the whole range from one raw stream.',
        },
        {
          type: 'paragraph',
          text: 'Two problems shape the process. Onion tissue browns as it dries, from reactions between its own sugars and amino acids, and the drier and hotter the material gets the faster that runs — so the endgame of drying is a balance between removing water and keeping the product pale. Onion flavour is also volatile and is generated by enzyme action when tissue is cut; some of it inevitably leaves with the steam. How much survives is a real difference between plants and a genuine quality variable in the trade.',
        },
      ],
    },
    {
      id: 'quality-and-storage',
      heading: 'Quality, storage, and use',
      body: [
        {
          type: 'paragraph',
          text: 'Buyers specify particle size and its uniformity, colour and freedom from scorched or browned pieces, pungency or flavour strength, residual moisture, rehydration behaviour, and microbiological condition. Colour is watched closely because it is the visible record of how well the drying was controlled, and because dark specks in a pale powder are conspicuous in a finished food.',
        },
        {
          type: 'paragraph',
          text: 'The dominant storage property is that the product is strongly hygroscopic — it pulls moisture from the air, and it does so eagerly. Water taken back up causes caking, restarts browning, and undoes the stability the drying paid for, so dehydrated onion is packed in moisture-barrier containers and kept sealed and dry. It also carries a penetrating aroma that transfers readily to other goods, which makes segregated storage a practical requirement rather than a nicety.',
        },
        {
          type: 'list',
          items: [
            'Food manufacturing — the dominant use, in soups, sauces, seasonings, snacks, and prepared foods',
            'Food service and retail — packed as a dried culinary ingredient',
          ],
        },
        {
          type: 'callout',
          tone: 'caution',
          title: 'No moisture or process figures are given here',
          text: 'Residual moisture targets, drying temperatures and stage profiles, and particle-size bands for each traded format are set by the plant, the applicable standard, and the purchase contract. AgricultureID does not reproduce them.',
        },
      ],
    },
  ],
  primaryUses: ['food'],
  majorQualityAttributes: [
    'Particle size and uniformity',
    'Colour and freedom from scorched pieces',
    'Pungency and flavour retention',
    'Residual moisture content',
    'Rehydration behaviour',
    'Microbiological condition',
  ],
  processContext:
    'Produced by topping, peeling, slicing, and staged belt-drying of cured bulbs, then screening and milling of the dried material into flakes, granules, and powder; drying is controlled to limit browning and flavour loss.',
  storageContext:
    'Strongly hygroscopic; packed in moisture-barrier containers and held sealed, cool, and dry, since moisture uptake causes caking and browning. Its penetrating aroma makes segregated storage necessary.',
  connections: [
    { type: 'crop', slug: 'onion' },
    { type: 'post-harvest', slug: 'sun-drying' },
    { type: 'post-harvest', slug: 'packing-and-packaging' },
    { type: 'post-harvest', slug: 'moisture-content-and-equilibrium' },
  ],
  imageIdentity: 'unavailable',
  glossaryTerms: ['cultivar'],
  sourceReferences: [
    {
      sourceId: 'fao',
      citedFor:
        'Vegetable dehydration pathways and dried onion as a traded ingredient',
    },
    {
      sourceId: 'usda-ars',
      citedFor:
        'Onion dehydration, browning during drying, and flavour volatility',
    },
    {
      sourceId: 'usda',
      citedFor: 'Dehydrated onion product formats and quality attributes',
    },
    {
      sourceId: 'cornell-cals',
      citedFor:
        'High-solids onion cultivars grown for processing and dehydration',
    },
  ],
  updatedAt: '2026-07-13',
  reviewedAt: '2026-07-13',
  geographicScope:
    'Global. Product naming, particle-size classes, and food-safety requirements for dried vegetable ingredients are jurisdiction-specific.',
  limitations: [
    'This is a reference description of the product, not a processing specification, formulation, or food-standards compliance statement.',
    'No moisture, drying temperature, particle-size, or pungency figures are given here — they are plant-, standard-, and contract-specific.',
    'Format naming for flakes, granules, and powder differs between suppliers and markets; the contract definition governs.',
  ],
  editorialStatus: 'published',
  seo: {
    title: 'Dehydrated Onion: Primary Product of Onion Drying',
    description:
      'Dehydrated onion as a commodity product: the high-solids cultivars used, staged drying and browning control, flake to powder formats, and hygroscopic storage.',
    keywords: [
      'dehydrated onion',
      'onion flakes',
      'onion powder',
      'onion dehydration',
      'high-solids onions',
    ],
  },
  structuredData: { article: true },
};
