import type { CommodityProductContent } from '@/types/content';

export const rawSugar: CommodityProductContent = {
  id: 'commodity-product-raw-sugar',
  slug: 'raw-sugar',
  contentType: 'commodity-product',
  title: 'Raw Sugar',
  alternativeNames: ['Raw cane sugar', 'Centrifugal raw sugar', 'VHP sugar'],
  category: 'Primary manufactured product',
  subcategory: 'Partially purified cane sugar crystals',
  productClass: 'primary-product',
  derivedFrom: { type: 'commodity', slug: 'sugarcane' },
  physicalForm: 'crystal',
  summary:
    'Raw sugar is the golden-brown crystal a cane mill produces: sucrose crystallised out of cane juice and spun free of most, but not all, of its mother liquor. It is the world’s traded sugar commodity, shipped in bulk to refineries that finish it into white sugar.',
  introduction: [
    {
      type: 'paragraph',
      text: 'Raw sugar is what a cane mill exists to make. Juice pressed from the cane is clarified, boiled down, and crystallised, and the crystals are spun in centrifuges to throw off the syrup around them. What remains is a sucrose crystal still wearing a thin film of that syrup — which is what gives raw sugar its colour, its faint molasses smell, and its name.',
    },
    {
      type: 'paragraph',
      text: 'It is deliberately unfinished. A cane mill stops here because the last stages of purification are a different business, done at a different scale, usually in the country where the sugar will be eaten. The result is one of the great bulk commodities of maritime trade: raw sugar moves by the shipload, and it is the reason a cane-growing country can sell sweetness to a country that grows none.',
    },
  ],
  keyFacts: [
    { label: 'Product class', value: 'Primary product of cane milling' },
    { label: 'Made from', value: 'Sugarcane (Saccharum spp. hybrids)' },
    {
      label: 'What it is',
      value: 'Sucrose crystals carrying a film of mother liquor',
    },
    {
      label: 'Traded on',
      value: 'A polarisation basis defined by the contract',
    },
    { label: 'Shipped as', value: 'Bulk cargo, in ships’ holds' },
    {
      label: 'Next step',
      value: 'Refining into white sugar, usually at destination',
    },
    {
      label: 'Simultaneous streams',
      value: 'Molasses (co-product) and bagasse (by-product)',
    },
  ],
  sections: [
    {
      id: 'what-it-is',
      heading: 'What raw sugar is',
      body: [
        {
          type: 'paragraph',
          text: 'Crystallisation is a purification. As sucrose comes out of a boiling syrup it forms an orderly crystal that excludes most of the impurities around it, so the crystal is far purer than the liquid it grew in. Centrifuging then removes the bulk of that liquid. But the film clinging to each crystal is not removed, and it is that residue — not the crystal — that makes raw sugar brown.',
        },
        {
          type: 'paragraph',
          text: 'This matters for a common misunderstanding. The colour of raw sugar is a coating of impurities, not a property of the sucrose inside it; the sucrose in raw sugar, refined white sugar, and beet sugar is the same molecule. Mills producing for export often aim for a higher-purity crystal, known in the trade as very high polarisation sugar, precisely because a cleaner raw sugar travels and refines better.',
        },
        {
          type: 'callout',
          tone: 'note',
          title: 'Raw sugar is not unrefined speciality sugar',
          text: 'Bulk raw sugar is a refinery feedstock, not a retail product. The brown speciality sugars sold to consumers are separate goods made by other routes, and the shared word "raw" does not make them the same commodity.',
        },
      ],
    },
    {
      id: 'polarisation',
      heading: 'Polarisation: how raw sugar is described',
      body: [
        {
          type: 'paragraph',
          text: 'Sucrose rotates the plane of polarised light by a fixed and characteristic amount, and that behaviour became the basis for measuring it long before modern analytical chemistry existed. Polarisation — pol, in the trade — is the measurement of sucrose content by that optical rotation, and it remains the central term of the raw sugar trade.',
        },
        {
          type: 'paragraph',
          text: 'Raw sugar contracts are written on a polarisation basis, with the delivered sugar’s polarisation compared against the contract basis and the price adjusted accordingly: a consignment testing above basis earns a premium, one below it a deduction. Moisture, ash, colour, and the presence of dextran — the gum generated by microbial action on stale cane — are also assessed, since each affects what a refinery can do with the cargo. The specific bases, tolerances, and adjustment scales belong to the contracts and are not reproduced here.',
        },
      ],
    },
    {
      id: 'bulk-shipping',
      heading: 'Bulk shipping and storage',
      body: [
        {
          type: 'paragraph',
          text: 'Raw sugar is one of the few food commodities carried as a loose bulk cargo in a ship’s hold, poured in at a bulk terminal and grabbed out at the other end. That is only possible because the crystal is robust and the cargo is destined for a refinery that will dissolve it anyway — white sugar, by contrast, is bagged, because its cleanliness is the product.',
        },
        {
          type: 'paragraph',
          text: 'Sugar is hygroscopic, and a bulk pile of it is unforgiving of moisture. Damp raw sugar cakes into a mass that must be broken out rather than discharged, and it deteriorates: micro-organisms in the syrup film become active as moisture rises, and the pile can heat and lose sugar. Terminals therefore control the moisture and temperature of sugar going into store and monitor the pile, and cargoes are assessed on moisture as a matter of course.',
        },
      ],
    },
    {
      id: 'refining-and-companions',
      heading: 'Refining, and the streams alongside',
      body: [
        {
          type: 'paragraph',
          text: 'At the refinery, the syrup film is washed off the crystal, and the sugar is then dissolved, clarified, decolourised, and recrystallised into white sugar. The separation of milling from refining is the structural fact of the world sugar trade: cane mills sit in the cane, refineries sit near consumers or ports, and raw sugar is the form in which the product travels between them.',
        },
        {
          type: 'paragraph',
          text: 'Raw sugar is never made alone. The same crystallisation that produces it leaves molasses — the liquor from which no more sugar can economically be recovered — and the same crushing that released the juice leaves bagasse. How much sugar the mill drives into crystal rather than leaving in the molasses is an operating decision, which is why these streams are related and not independent.',
        },
      ],
    },
  ],
  primaryUses: ['food'],
  majorQualityAttributes: [
    'Polarisation (sucrose content)',
    'Moisture content',
    'Colour',
    'Ash content',
    'Dextran content',
    'Grain size and uniformity',
  ],
  processContext:
    'Produced at a cane mill by clarifying and evaporating cane juice, crystallising sucrose from the syrup, and centrifuging the crystals free of most of their mother liquor.',
  storageContext:
    'Held in bulk sugar sheds and silos and shipped as loose bulk cargo; hygroscopic, so it cakes, heats, and deteriorates if moisture is not controlled going into store.',
  commodityCodes: [
    {
      system: 'HS',
      code: '1701.14',
      version: 'HS 2022',
      sourceId: 'worldbank',
      note: 'Other cane sugar, raw, not containing added flavouring or colouring matter — the bulk raw sugar of international trade.',
    },
  ],
  connections: [
    { type: 'crop', slug: 'sugarcane' },
    { type: 'machinery', slug: 'sugarcane-harvester' },
  ],
  relatedTopics: [
    { type: 'commodity-product', slug: 'molasses' },
    { type: 'commodity-product', slug: 'beet-sugar' },
  ],
  imageIdentity: 'unavailable',
  sourceReferences: [
    {
      sourceId: 'fao',
      citedFor:
        'Raw sugar as the traded sugar commodity and the milling-to-refining pathway',
    },
    {
      sourceId: 'usda-ers',
      citedFor:
        'Sugar sector structure, raw sugar trade, and refining separation',
    },
    {
      sourceId: 'embrapa',
      citedFor: 'Cane milling, crystallisation, and product streams',
    },
  ],
  updatedAt: '2026-07-13',
  reviewedAt: '2026-07-13',
  geographicScope:
    'Global. Contract bases, polarisation adjustment scales, and sugar trade regimes are contract- and jurisdiction-specific.',
  limitations: [
    'This is a reference description of the product, not a contract specification, refinery specification, or customs classification.',
    'No polarisation bases, moisture limits, colour figures, or recovery rates are given here — they belong to the applicable contract and standard.',
    'Sugar trade is subject to jurisdiction-specific quota, tariff, and preference regimes that this entry does not describe.',
  ],
  editorialStatus: 'published',
  seo: {
    title: 'Raw Sugar: The Cane Mill’s Traded Crystal',
    description:
      'Raw sugar as a commodity product: sucrose crystals still filmed with mother liquor, traded on polarisation, shipped as bulk cargo, and refined into white sugar.',
    keywords: [
      'raw sugar',
      'polarisation',
      'VHP sugar',
      'bulk sugar shipping',
      'sugar refining',
    ],
  },
  structuredData: { article: true },
};
