import type { FarmingSystemContent } from '@/types/content';

export const precisionAgriculture: FarmingSystemContent = {
  id: 'system-precision-agriculture',
  slug: 'precision-agriculture',
  contentType: 'farming-system',
  title: 'Precision Agriculture',
  systemClass: 'production-approach',
  alternativeNames: ['Precision farming', 'Site-specific crop management'],
  category: 'Farming system',
  subcategory: 'Production approach',
  summary:
    'Precision agriculture uses positioning, sensing, and data-management technologies to match inputs and field operations to within-field variability, rather than applying a single uniform rate across an entire field.',
  introduction: [
    {
      type: 'paragraph',
      text: 'Precision agriculture is an approach to input and operations management built around measuring how conditions vary within a field — soil type, fertility, moisture, pest pressure, yield potential — and adjusting seeding, fertilizer, water, and pesticide application accordingly, instead of treating a whole field as uniform. Core tools include GPS/GNSS guidance, yield monitors, remote sensing and drone imagery, and variable-rate application equipment.',
    },
    {
      type: 'paragraph',
      text: 'The term covers a broad and evolving range of sophistication, from simple GPS auto-steer and guidance that reduces overlap, to advanced data platforms combining multiple sensor layers with software-generated prescriptions. Precision agriculture is not a separate philosophy of production in the way organic farming is; it is a management approach that can be layered onto conventional, organic, conservation, or other systems.',
    },
  ],
  keyFacts: [
    {
      label: 'Core aim',
      value: 'Match inputs and operations to within-field variability',
    },
    {
      label: 'Key technologies',
      value:
        'GPS/GNSS guidance, yield monitors, remote sensing, variable-rate application',
    },
    {
      label: 'Data role',
      value: 'Relies on field mapping and data management to guide decisions',
    },
    {
      label: 'Definition status',
      value:
        'Broad, evolving term spanning simple guidance to advanced data analytics',
    },
    {
      label: 'Compatibility',
      value:
        'Can be combined with conventional, organic, or conservation systems',
    },
    {
      label: 'Adoption driver',
      value:
        'Often justified by input-use efficiency, not by a yield increase alone',
    },
  ],
  sections: [
    {
      id: 'what-precision-agriculture-is',
      heading: 'What precision agriculture is',
      body: [
        {
          type: 'paragraph',
          text: 'At its core, precision agriculture treats a field as a mosaic of zones with different soil, fertility, and pest conditions rather than a single uniform unit, and uses data and technology to apply the right input, at the right rate, in the right place and time.',
        },
        {
          type: 'callout',
          tone: 'note',
          text: 'The term spans a wide range: a farm using only GPS auto-steer for straighter passes and a farm using satellite imagery, soil sensors, and automated variable-rate prescriptions are both commonly described as practicing precision agriculture, at very different levels of sophistication.',
        },
      ],
    },
    {
      id: 'key-technologies',
      heading: 'Key technologies',
      body: [
        {
          type: 'list',
          items: [
            'GPS/GNSS guidance and auto-steer, reducing overlap and skips during field operations',
            'Yield monitors that record output at fine spatial resolution during harvest',
            'Remote sensing and drone imagery for crop health, moisture, or stand assessment',
            'Variable-rate application equipment for seed, fertilizer, and crop-protection products',
            'Soil sampling and sensor-based mapping to characterize field variability',
          ],
        },
      ],
    },
    {
      id: 'how-it-works',
      heading: 'How it works',
      body: [
        {
          type: 'paragraph',
          text: 'A typical precision-agriculture cycle collects field data (soil samples, yield maps, imagery), analyzes it to identify management zones, generates a prescription map for seeding or input rates, applies that prescription with guided or automated equipment, and then evaluates the outcome — feeding results back into the next season’s decisions.',
        },
        {
          type: 'definitionList',
          items: [
            {
              term: 'Yield map',
              description:
                'A spatial record of harvested yield across a field, generated by a yield monitor.',
            },
            {
              term: 'Prescription map',
              description:
                'A digital map instructing equipment to vary input rates by location.',
            },
            {
              term: 'Variable-rate application (VRT)',
              description:
                'Applying seed, fertilizer, or crop protection at rates that change across a field rather than a single flat rate.',
            },
          ],
        },
      ],
    },
    {
      id: 'data-and-decision-making',
      heading: 'Data and decision-making',
      body: [
        {
          type: 'paragraph',
          text: 'Collecting data is only part of precision agriculture; turning it into a sound agronomic decision requires interpretation, since raw sensor or yield data does not by itself explain why variability occurs. Data management, interoperability between equipment brands, and access to agronomic expertise are practical challenges alongside the technology itself.',
        },
        {
          type: 'table',
          caption: 'Common technologies and their primary use',
          columns: ['Technology', 'Primary use'],
          rows: [
            [
              'GPS/GNSS guidance',
              'Reduce overlap and improve accuracy of field passes',
            ],
            ['Yield monitor', 'Record spatial yield variability at harvest'],
            [
              'Remote sensing / drone imagery',
              'Assess crop health, stand, or moisture status during the season',
            ],
            [
              'Variable-rate applicator',
              'Apply seed, fertilizer, or crop protection at a rate that varies by zone',
            ],
          ],
        },
      ],
    },
    {
      id: 'benefits-and-trade-offs',
      heading: 'Benefits and trade-offs',
      body: [
        {
          type: 'list',
          items: [
            'Can improve input-use efficiency by directing inputs to where they are needed',
            'Reduces overlap and waste in field operations',
            'Supports detailed record-keeping and traceability',
            'Enables more targeted pest and disease management',
          ],
        },
        {
          type: 'list',
          items: [
            'Requires upfront investment in equipment, software, and often subscriptions',
            'Benefits scale with farm size and the degree of within-field variability, and are smaller on uniform or small fields',
            'Requires data-management skills and reliable connectivity',
            'Interpreting data into sound agronomic decisions is not automatic',
          ],
        },
        {
          type: 'callout',
          tone: 'important',
          text: 'This entry does not provide return-on-investment or yield figures for precision agriculture. Economic outcomes depend heavily on farm scale, field variability, crop, and how well data is used, and cannot be generalized to a single number.',
        },
      ],
    },
    {
      id: 'where-it-is-used',
      heading: 'Where it is used',
      body: [
        {
          type: 'paragraph',
          text: 'Precision-agriculture technologies are most established in large-scale, mechanized row-crop production where equipment and connectivity investments are more easily justified, but simpler tools such as GPS guidance are used across a much broader range of farm sizes. Adoption is uneven worldwide and depends heavily on equipment cost, connectivity infrastructure, and access to technical support and extension services.',
        },
      ],
    },
  ],
  relatedTopics: [
    { type: 'farming-system', slug: 'conservation-agriculture' },
    { type: 'farming-system', slug: 'regenerative-agriculture' },
  ],
  connections: [
    { type: 'machinery', slug: 'gps-guidance-system' },
    { type: 'machinery', slug: 'agricultural-drone' },
    { type: 'machinery', slug: 'sprayer' },
    { type: 'machinery', slug: 'tractor' },
    { type: 'soil-topic', slug: 'soil-testing' },
    { type: 'crop', slug: 'maize' },
    { type: 'crop', slug: 'wheat' },
    { type: 'crop', slug: 'soybean' },
  ],
  glossaryTerms: ['agronomy', 'yield', 'integrated-pest-management'],
  geographicScope:
    'Precision-agriculture technologies are used across many farming systems worldwide, though adoption depends on equipment cost, connectivity, and technical support, and varies significantly by region and farm scale.',
  limitations: [
    'Precision agriculture is an umbrella term covering a wide range of technologies and sophistication levels; this entry describes common elements rather than one fixed system.',
    'Benefits depend on field variability, farm scale, and how well data is interpreted agronomically — this entry does not provide universal return-on-investment figures.',
  ],
  sourceReferences: [
    {
      sourceId: 'fao',
      citedFor: 'Digital and precision technologies in agriculture',
    },
    {
      sourceId: 'usda-nrcs',
      citedFor: 'Precision conservation and site-specific management context',
    },
    {
      sourceId: 'cgiar',
      citedFor: 'Research on data-driven and site-specific crop management',
    },
    {
      sourceId: 'ec-agri',
      citedFor: 'Policy context for digital farming technologies',
    },
  ],
  reviewedAt: '2026-07-12',
  updatedAt: '2026-07-12',
  editorialStatus: 'published',
  seo: {
    title: 'Precision Agriculture',
    description:
      'Precision agriculture explained: GPS guidance, yield mapping, remote sensing, and variable-rate application, with honest benefits, costs, and limitations.',
    keywords: [
      'precision agriculture',
      'precision farming',
      'variable-rate application',
      'GPS guidance',
    ],
  },
  structuredData: { article: true },
};
