import type { PostHarvestContent } from '@/types/content';

export const ethyleneManagement: PostHarvestContent = {
  id: 'post-harvest-ethylene-management',
  slug: 'ethylene-management',
  contentType: 'post-harvest',
  title: 'Ethylene Management',
  postHarvestClass: 'quality',
  alternativeNames: ['Ethylene control', 'Ethylene scrubbing'],
  category: 'Post-harvest operation',
  subcategory: 'Quality management',
  summary:
    'Ethylene management controls the ripening plant hormone ethylene in stores and transport — separating producers from sensitive crops, ventilating or scrubbing it away, and sometimes blocking its action — to slow ripening and reduce quality loss.',
  introduction: [
    {
      type: 'paragraph',
      text: 'Ethylene is a naturally produced plant hormone that, even in very small amounts, triggers and accelerates ripening, senescence, and quality changes in many fruits and vegetables. Some produce releases a great deal of ethylene as it ripens, while other produce is highly sensitive to it, so managing ethylene around stored produce is an important part of preserving quality.',
    },
    {
      type: 'paragraph',
      text: 'Ethylene management can work in two directions. Where the aim is to slow ripening, ethylene is kept low by separating high-producing crops from sensitive ones, ventilating stores, removing (scrubbing) ethylene, or applying inhibitors that block its action. Where ripening is wanted on schedule, ethylene is instead applied deliberately in controlled ripening rooms.',
    },
  ],
  keyFacts: [
    {
      label: 'What it is',
      value:
        'The plant hormone ethylene, which promotes ripening and senescence',
    },
    {
      label: 'Active at',
      value: 'Very low concentrations, so small sources can matter',
    },
    {
      label: 'To slow ripening',
      value:
        'Separate producers from sensitive crops, ventilate, scrub, or inhibit',
    },
    {
      label: 'To promote ripening',
      value: 'Apply ethylene in controlled ripening rooms',
    },
    {
      label: 'Also generated by',
      value: 'Some combustion sources and stressed or damaged produce',
    },
    {
      label: 'Key pairing rule',
      value:
        'Keep high ethylene producers away from ethylene-sensitive produce',
    },
  ],
  sections: [
    {
      id: 'why-it-matters',
      heading: 'Why ethylene matters after harvest',
      body: [
        {
          type: 'paragraph',
          text: 'Ethylene coordinates ripening in climacteric fruit and drives changes such as softening, colour change, yellowing of green vegetables, and shortened shelf life. Because it acts at very low concentrations and moves freely as a gas, ethylene given off by ripening fruit in a mixed store can prematurely ripen or spoil sensitive produce stored nearby. Damaged, decaying, and stressed produce, and some combustion sources such as engine exhaust, can also raise ethylene levels.',
        },
        {
          type: 'paragraph',
          text: 'The practical consequence is that produce should be grouped thoughtfully. High ethylene producers — many ripening fruits — are best kept apart from ethylene-sensitive items such as many leafy vegetables and unripe or long-storage crops.',
        },
      ],
    },
    {
      id: 'controlling',
      heading: 'Controlling ethylene',
      body: [
        {
          type: 'definitionList',
          items: [
            {
              term: 'Separation',
              description:
                'Store and transport high ethylene producers apart from sensitive produce to prevent cross-exposure.',
            },
            {
              term: 'Ventilation and low temperature',
              description:
                'Fresh air dilutes ethylene, and cold storage both slows ethylene production and reduces the produce’s sensitivity to it.',
            },
            {
              term: 'Scrubbing / removal',
              description:
                'Ethylene is removed from store air by absorbers or catalytic and other scrubbing systems.',
            },
            {
              term: 'Action inhibitors',
              description:
                'Compounds that block ethylene’s action can be applied to slow ripening of some crops, under label and regulatory conditions.',
            },
          ],
        },
        {
          type: 'paragraph',
          text: 'These tools are combined according to the produce and the goal. For long-term storage of ethylene-sensitive crops, keeping ethylene low is often as important as keeping the temperature correct.',
        },
      ],
    },
    {
      id: 'ripening-use',
      heading: 'Using ethylene to ripen on schedule',
      body: [
        {
          type: 'paragraph',
          text: 'For fruits that are harvested mature but unripe and ripened near the market — such as bananas and some other climacteric fruit — ethylene is applied deliberately in controlled ripening rooms to bring the fruit to eating condition uniformly and on schedule. This is the mirror image of ethylene removal, using the same hormone to speed rather than slow ripening.',
        },
        {
          type: 'callout',
          tone: 'note',
          title: 'Two goals, one hormone',
          text: 'The same molecule is scrubbed away to extend storage of some crops and added on purpose to ripen others; management depends on the commodity and the objective.',
        },
      ],
    },
  ],
  connections: [
    { type: 'crop', slug: 'banana' },
    { type: 'crop', slug: 'apple' },
    { type: 'crop', slug: 'tomato' },
    { type: 'crop', slug: 'lettuce' },
  ],
  relatedTopics: [
    { type: 'post-harvest', slug: 'fruit-ripening' },
    { type: 'post-harvest', slug: 'controlled-atmosphere-storage' },
    { type: 'post-harvest', slug: 'cold-storage' },
    { type: 'post-harvest', slug: 'modified-atmosphere-packaging' },
  ],
  sourceReferences: [
    {
      sourceId: 'usda-ars',
      citedFor: 'Ethylene physiology and post-harvest management research',
    },
    {
      sourceId: 'fao',
      citedFor: 'Ethylene and ripening in post-harvest handling',
    },
    {
      sourceId: 'ahdb',
      citedFor: 'Ethylene control in fruit and vegetable storage',
    },
  ],
  updatedAt: '2026-07-13',
  reviewedAt: '2026-07-13',
  geographicScope:
    'Global. Ethylene sensitivity and production vary widely by commodity and ripening physiology.',
  limitations: [
    'Ethylene production and sensitivity are commodity- and ripeness-specific; this entry gives principles, not per-crop thresholds.',
    'Ethylene action inhibitors and scrubbing technologies are subject to registration and label conditions that vary by country and crop.',
    'Effective management depends on correct temperature and store design as well as on ethylene control itself.',
  ],
  editorialStatus: 'published',
  seo: {
    title: 'Ethylene Management in Post-Harvest Storage',
    description:
      'Managing ethylene, the ripening hormone, after harvest — separation, ventilation, scrubbing, and inhibitors to slow ripening, or ripening rooms to speed it up.',
    keywords: [
      'ethylene management',
      'ripening hormone',
      'ethylene scrubbing',
      'ethylene sensitive produce',
      'post-harvest quality',
    ],
  },
  structuredData: { article: true },
};
